// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rocev2_top_mq_meta_table_ap_uint_64_2048_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        mq_metaReqFifo_dout,
        mq_metaReqFifo_num_data_valid,
        mq_metaReqFifo_fifo_cap,
        mq_metaReqFifo_empty_n,
        mq_metaReqFifo_read,
        mq_metaRspFifo_din,
        mq_metaRspFifo_num_data_valid,
        mq_metaRspFifo_fifo_cap,
        mq_metaRspFifo_full_n,
        mq_metaRspFifo_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [255:0] mq_metaReqFifo_dout;
input  [1:0] mq_metaReqFifo_num_data_valid;
input  [1:0] mq_metaReqFifo_fifo_cap;
input   mq_metaReqFifo_empty_n;
output   mq_metaReqFifo_read;
output  [127:0] mq_metaRspFifo_din;
input  [1:0] mq_metaRspFifo_num_data_valid;
input  [1:0] mq_metaRspFifo_fifo_cap;
input   mq_metaRspFifo_full_n;
output   mq_metaRspFifo_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg mq_metaReqFifo_read;
reg mq_metaRspFifo_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] tmp_i_nbreadreq_fu_70_p3;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] tmp_i_reg_249;
reg   [0:0] req_write_reg_253;
reg   [0:0] req_append_reg_257;
reg    ap_predicate_op55_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg   [10:0] meta_table_value_V_address0;
reg    meta_table_value_V_ce0;
reg    meta_table_value_V_we0;
wire   [63:0] meta_table_value_V_d0;
wire   [63:0] meta_table_value_V_q0;
wire   [10:0] meta_table_next_V_address0;
reg    meta_table_next_V_ce0;
reg    meta_table_next_V_we0;
wire   [15:0] meta_table_next_V_d0;
wire   [15:0] meta_table_next_V_q0;
reg   [10:0] meta_table_valid_address0;
reg    meta_table_valid_ce0;
reg    meta_table_valid_we0;
wire   [0:0] meta_table_valid_d0;
wire   [0:0] meta_table_valid_q0;
wire   [10:0] meta_table_isTail_address0;
reg    meta_table_isTail_ce0;
reg    meta_table_isTail_we0;
reg   [0:0] meta_table_isTail_d0;
wire   [0:0] meta_table_isTail_q0;
reg    mq_metaReqFifo_blk_n;
wire    ap_block_pp0_stage0;
reg    mq_metaRspFifo_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] req_write_fu_204_p3;
wire   [0:0] req_append_fu_212_p3;
wire   [63:0] zext_ln541_fu_220_p1;
wire   [10:0] meta_table_value_V_addr_gep_fu_144_p3;
wire   [10:0] meta_table_valid_addr_gep_fu_151_p3;
reg    ap_block_pp0_stage0_01001;
wire   [10:0] req_idx_V_fu_160_p1;
wire   [88:0] tmp_134_i_fu_230_p6;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_123;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

rocev2_top_mq_meta_table_ap_uint_64_2048_s_meta_table_value_V_RAM_T2P_BRAM_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
meta_table_value_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(meta_table_value_V_address0),
    .ce0(meta_table_value_V_ce0),
    .we0(meta_table_value_V_we0),
    .d0(meta_table_value_V_d0),
    .q0(meta_table_value_V_q0)
);

rocev2_top_mq_meta_table_ap_uint_64_2048_s_meta_table_next_V_RAM_T2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
meta_table_next_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(meta_table_next_V_address0),
    .ce0(meta_table_next_V_ce0),
    .we0(meta_table_next_V_we0),
    .d0(meta_table_next_V_d0),
    .q0(meta_table_next_V_q0)
);

rocev2_top_mq_meta_table_ap_uint_64_2048_s_meta_table_valid_RAM_T2P_BRAM_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
meta_table_valid_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(meta_table_valid_address0),
    .ce0(meta_table_valid_ce0),
    .we0(meta_table_valid_we0),
    .d0(meta_table_valid_d0),
    .q0(meta_table_valid_q0)
);

rocev2_top_mq_meta_table_ap_uint_64_2048_s_meta_table_valid_RAM_T2P_BRAM_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
meta_table_isTail_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(meta_table_isTail_address0),
    .ce0(meta_table_isTail_ce0),
    .we0(meta_table_isTail_we0),
    .d0(meta_table_isTail_d0),
    .q0(meta_table_isTail_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        req_append_reg_257 <= mq_metaReqFifo_dout[256'd200];
        req_write_reg_253 <= mq_metaReqFifo_dout[256'd192];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_i_reg_249 <= tmp_i_nbreadreq_fu_70_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_append_fu_212_p3 == 1'd1) & (req_write_fu_204_p3 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_write_fu_204_p3 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_append_fu_212_p3 == 1'd0) & (req_write_fu_204_p3 == 1'd0)))) begin
        meta_table_isTail_ce0 = 1'b1;
    end else begin
        meta_table_isTail_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_123)) begin
        if ((req_write_fu_204_p3 == 1'd1)) begin
            meta_table_isTail_d0 = mq_metaReqFifo_dout[256'd152];
        end else if (((req_append_fu_212_p3 == 1'd1) & (req_write_fu_204_p3 == 1'd0))) begin
            meta_table_isTail_d0 = 1'd0;
        end else begin
            meta_table_isTail_d0 = 'bx;
        end
    end else begin
        meta_table_isTail_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_append_fu_212_p3 == 1'd1) & (req_write_fu_204_p3 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_write_fu_204_p3 == 1'd1)))) begin
        meta_table_isTail_we0 = 1'b1;
    end else begin
        meta_table_isTail_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_append_fu_212_p3 == 1'd1) & (req_write_fu_204_p3 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_write_fu_204_p3 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_append_fu_212_p3 == 1'd0) & (req_write_fu_204_p3 == 1'd0)))) begin
        meta_table_next_V_ce0 = 1'b1;
    end else begin
        meta_table_next_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_append_fu_212_p3 == 1'd1) & (req_write_fu_204_p3 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_write_fu_204_p3 == 1'd1)))) begin
        meta_table_next_V_we0 = 1'b1;
    end else begin
        meta_table_next_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_123)) begin
        if ((req_write_fu_204_p3 == 1'd1)) begin
            meta_table_valid_address0 = meta_table_valid_addr_gep_fu_151_p3;
        end else if (((req_append_fu_212_p3 == 1'd0) & (req_write_fu_204_p3 == 1'd0))) begin
            meta_table_valid_address0 = zext_ln541_fu_220_p1;
        end else begin
            meta_table_valid_address0 = 'bx;
        end
    end else begin
        meta_table_valid_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_write_fu_204_p3 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_append_fu_212_p3 == 1'd0) & (req_write_fu_204_p3 == 1'd0)))) begin
        meta_table_valid_ce0 = 1'b1;
    end else begin
        meta_table_valid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_write_fu_204_p3 == 1'd1))) begin
        meta_table_valid_we0 = 1'b1;
    end else begin
        meta_table_valid_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_123)) begin
        if ((req_write_fu_204_p3 == 1'd1)) begin
            meta_table_value_V_address0 = meta_table_value_V_addr_gep_fu_144_p3;
        end else if (((req_append_fu_212_p3 == 1'd0) & (req_write_fu_204_p3 == 1'd0))) begin
            meta_table_value_V_address0 = zext_ln541_fu_220_p1;
        end else begin
            meta_table_value_V_address0 = 'bx;
        end
    end else begin
        meta_table_value_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_write_fu_204_p3 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_append_fu_212_p3 == 1'd0) & (req_write_fu_204_p3 == 1'd0)))) begin
        meta_table_value_V_ce0 = 1'b1;
    end else begin
        meta_table_value_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (req_write_fu_204_p3 == 1'd1))) begin
        meta_table_value_V_we0 = 1'b1;
    end else begin
        meta_table_value_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mq_metaReqFifo_blk_n = mq_metaReqFifo_empty_n;
    end else begin
        mq_metaReqFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mq_metaReqFifo_read = 1'b1;
    end else begin
        mq_metaReqFifo_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op55_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mq_metaRspFifo_blk_n = mq_metaRspFifo_full_n;
    end else begin
        mq_metaRspFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op55_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mq_metaRspFifo_write = 1'b1;
    end else begin
        mq_metaRspFifo_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_predicate_op55_write_state2 == 1'b1) & (mq_metaRspFifo_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (mq_metaReqFifo_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_predicate_op55_write_state2 == 1'b1) & (mq_metaRspFifo_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (mq_metaReqFifo_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_predicate_op55_write_state2 == 1'b1) & (mq_metaRspFifo_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (mq_metaReqFifo_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (mq_metaReqFifo_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op55_write_state2 == 1'b1) & (mq_metaRspFifo_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_123 = ((1'b0 == ap_block_pp0_stage0) & (tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

always @ (*) begin
    ap_predicate_op55_write_state2 = ((req_append_reg_257 == 1'd0) & (req_write_reg_253 == 1'd0) & (tmp_i_reg_249 == 1'd1));
end

assign meta_table_isTail_address0 = zext_ln541_fu_220_p1;

assign meta_table_next_V_address0 = zext_ln541_fu_220_p1;

assign meta_table_next_V_d0 = {{mq_metaReqFifo_dout[143:128]}};

assign meta_table_valid_addr_gep_fu_151_p3 = zext_ln541_fu_220_p1;

assign meta_table_valid_d0 = mq_metaReqFifo_dout[256'd144];

assign meta_table_value_V_addr_gep_fu_144_p3 = zext_ln541_fu_220_p1;

assign meta_table_value_V_d0 = {{mq_metaReqFifo_dout[127:64]}};

assign mq_metaRspFifo_din = tmp_134_i_fu_230_p6;

assign req_append_fu_212_p3 = mq_metaReqFifo_dout[256'd200];

assign req_idx_V_fu_160_p1 = mq_metaReqFifo_dout[10:0];

assign req_write_fu_204_p3 = mq_metaReqFifo_dout[256'd192];

assign tmp_134_i_fu_230_p6 = {{{{{meta_table_isTail_q0}, {7'd0}}, {meta_table_valid_q0}}, {meta_table_next_V_q0}}, {meta_table_value_V_q0}};

assign tmp_i_nbreadreq_fu_70_p3 = mq_metaReqFifo_empty_n;

assign zext_ln541_fu_220_p1 = req_idx_V_fu_160_p1;

endmodule //rocev2_top_mq_meta_table_ap_uint_64_2048_s
