// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rocev2_top_conn_table (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_axis_qp_conn_interface_TVALID,
        tx_ibhconnTable_req_dout,
        tx_ibhconnTable_req_num_data_valid,
        tx_ibhconnTable_req_fifo_cap,
        tx_ibhconnTable_req_empty_n,
        tx_ibhconnTable_req_read,
        tx_connTable2ibh_rsp_din,
        tx_connTable2ibh_rsp_num_data_valid,
        tx_connTable2ibh_rsp_fifo_cap,
        tx_connTable2ibh_rsp_full_n,
        tx_connTable2ibh_rsp_write,
        s_axis_qp_conn_interface_TDATA,
        s_axis_qp_conn_interface_TREADY
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   s_axis_qp_conn_interface_TVALID;
input  [15:0] tx_ibhconnTable_req_dout;
input  [1:0] tx_ibhconnTable_req_num_data_valid;
input  [1:0] tx_ibhconnTable_req_fifo_cap;
input   tx_ibhconnTable_req_empty_n;
output   tx_ibhconnTable_req_read;
output  [383:0] tx_connTable2ibh_rsp_din;
input  [3:0] tx_connTable2ibh_rsp_num_data_valid;
input  [3:0] tx_connTable2ibh_rsp_fifo_cap;
input   tx_connTable2ibh_rsp_full_n;
output   tx_connTable2ibh_rsp_write;
input  [183:0] s_axis_qp_conn_interface_TDATA;
output   s_axis_qp_conn_interface_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg tx_ibhconnTable_req_read;
reg tx_connTable2ibh_rsp_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] tmp_i_nbreadreq_fu_64_p3;
wire   [0:0] tmp_i_267_nbreadreq_fu_72_p3;
reg    ap_predicate_op17_read_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] tmp_i_reg_230;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg   [8:0] conn_table_remote_qpn_V_address0;
reg    conn_table_remote_qpn_V_ce0;
reg    conn_table_remote_qpn_V_we0;
wire   [23:0] conn_table_remote_qpn_V_d0;
wire   [23:0] conn_table_remote_qpn_V_q0;
reg   [8:0] conn_table_remote_ip_address_V_address0;
reg    conn_table_remote_ip_address_V_ce0;
reg    conn_table_remote_ip_address_V_we0;
wire   [127:0] conn_table_remote_ip_address_V_d0;
wire   [127:0] conn_table_remote_ip_address_V_q0;
reg   [8:0] conn_table_remote_udp_port_V_address0;
reg    conn_table_remote_udp_port_V_ce0;
reg    conn_table_remote_udp_port_V_we0;
wire   [15:0] conn_table_remote_udp_port_V_d0;
wire   [15:0] conn_table_remote_udp_port_V_q0;
reg    s_axis_qp_conn_interface_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    tx_ibhconnTable_req_blk_n;
reg    tx_connTable2ibh_rsp_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln541_7_fu_199_p1;
wire   [63:0] zext_ln541_fu_206_p1;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] ifRequest_qpn_V_fu_162_p1;
wire   [271:0] tmp_268_i_fu_213_p5;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_s_axis_qp_conn_interface_U_apdone_blk;
wire   [183:0] s_axis_qp_conn_interface_TDATA_int_regslice;
wire    s_axis_qp_conn_interface_TVALID_int_regslice;
reg    s_axis_qp_conn_interface_TREADY_int_regslice;
wire    regslice_both_s_axis_qp_conn_interface_U_ack_in;
reg    ap_condition_117;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

rocev2_top_conn_table_conn_table_remote_qpn_V_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 500 ),
    .AddressWidth( 9 ))
conn_table_remote_qpn_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conn_table_remote_qpn_V_address0),
    .ce0(conn_table_remote_qpn_V_ce0),
    .we0(conn_table_remote_qpn_V_we0),
    .d0(conn_table_remote_qpn_V_d0),
    .q0(conn_table_remote_qpn_V_q0)
);

rocev2_top_conn_table_conn_table_remote_ip_address_V_RAM_AUTO_1R1W #(
    .DataWidth( 128 ),
    .AddressRange( 500 ),
    .AddressWidth( 9 ))
conn_table_remote_ip_address_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conn_table_remote_ip_address_V_address0),
    .ce0(conn_table_remote_ip_address_V_ce0),
    .we0(conn_table_remote_ip_address_V_we0),
    .d0(conn_table_remote_ip_address_V_d0),
    .q0(conn_table_remote_ip_address_V_q0)
);

rocev2_top_conn_table_conn_table_remote_udp_port_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 500 ),
    .AddressWidth( 9 ))
conn_table_remote_udp_port_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conn_table_remote_udp_port_V_address0),
    .ce0(conn_table_remote_udp_port_V_ce0),
    .we0(conn_table_remote_udp_port_V_we0),
    .d0(conn_table_remote_udp_port_V_d0),
    .q0(conn_table_remote_udp_port_V_q0)
);

rocev2_top_regslice_both #(
    .DataWidth( 184 ))
regslice_both_s_axis_qp_conn_interface_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_qp_conn_interface_TDATA),
    .vld_in(s_axis_qp_conn_interface_TVALID),
    .ack_in(regslice_both_s_axis_qp_conn_interface_U_ack_in),
    .data_out(s_axis_qp_conn_interface_TDATA_int_regslice),
    .vld_out(s_axis_qp_conn_interface_TVALID_int_regslice),
    .ack_out(s_axis_qp_conn_interface_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_qp_conn_interface_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_i_reg_230 <= tmp_i_nbreadreq_fu_64_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_117)) begin
        if ((tmp_i_nbreadreq_fu_64_p3 == 1'd1)) begin
            conn_table_remote_ip_address_V_address0 = zext_ln541_fu_206_p1;
        end else if (((tmp_i_267_nbreadreq_fu_72_p3 == 1'd1) & (tmp_i_nbreadreq_fu_64_p3 == 1'd0))) begin
            conn_table_remote_ip_address_V_address0 = zext_ln541_7_fu_199_p1;
        end else begin
            conn_table_remote_ip_address_V_address0 = 'bx;
        end
    end else begin
        conn_table_remote_ip_address_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_64_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_267_nbreadreq_fu_72_p3 == 1'd1) & (tmp_i_nbreadreq_fu_64_p3 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        conn_table_remote_ip_address_V_ce0 = 1'b1;
    end else begin
        conn_table_remote_ip_address_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_267_nbreadreq_fu_72_p3 == 1'd1) & (tmp_i_nbreadreq_fu_64_p3 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conn_table_remote_ip_address_V_we0 = 1'b1;
    end else begin
        conn_table_remote_ip_address_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_117)) begin
        if ((tmp_i_nbreadreq_fu_64_p3 == 1'd1)) begin
            conn_table_remote_qpn_V_address0 = zext_ln541_fu_206_p1;
        end else if (((tmp_i_267_nbreadreq_fu_72_p3 == 1'd1) & (tmp_i_nbreadreq_fu_64_p3 == 1'd0))) begin
            conn_table_remote_qpn_V_address0 = zext_ln541_7_fu_199_p1;
        end else begin
            conn_table_remote_qpn_V_address0 = 'bx;
        end
    end else begin
        conn_table_remote_qpn_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_64_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_267_nbreadreq_fu_72_p3 == 1'd1) & (tmp_i_nbreadreq_fu_64_p3 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        conn_table_remote_qpn_V_ce0 = 1'b1;
    end else begin
        conn_table_remote_qpn_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_267_nbreadreq_fu_72_p3 == 1'd1) & (tmp_i_nbreadreq_fu_64_p3 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conn_table_remote_qpn_V_we0 = 1'b1;
    end else begin
        conn_table_remote_qpn_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_117)) begin
        if ((tmp_i_nbreadreq_fu_64_p3 == 1'd1)) begin
            conn_table_remote_udp_port_V_address0 = zext_ln541_fu_206_p1;
        end else if (((tmp_i_267_nbreadreq_fu_72_p3 == 1'd1) & (tmp_i_nbreadreq_fu_64_p3 == 1'd0))) begin
            conn_table_remote_udp_port_V_address0 = zext_ln541_7_fu_199_p1;
        end else begin
            conn_table_remote_udp_port_V_address0 = 'bx;
        end
    end else begin
        conn_table_remote_udp_port_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_64_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_267_nbreadreq_fu_72_p3 == 1'd1) & (tmp_i_nbreadreq_fu_64_p3 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        conn_table_remote_udp_port_V_ce0 = 1'b1;
    end else begin
        conn_table_remote_udp_port_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_267_nbreadreq_fu_72_p3 == 1'd1) & (tmp_i_nbreadreq_fu_64_p3 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conn_table_remote_udp_port_V_we0 = 1'b1;
    end else begin
        conn_table_remote_udp_port_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (ap_predicate_op17_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_qp_conn_interface_TDATA_blk_n = s_axis_qp_conn_interface_TVALID_int_regslice;
    end else begin
        s_axis_qp_conn_interface_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op17_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_qp_conn_interface_TREADY_int_regslice = 1'b1;
    end else begin
        s_axis_qp_conn_interface_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_i_reg_230 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tx_connTable2ibh_rsp_blk_n = tx_connTable2ibh_rsp_full_n;
    end else begin
        tx_connTable2ibh_rsp_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_reg_230 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tx_connTable2ibh_rsp_write = 1'b1;
    end else begin
        tx_connTable2ibh_rsp_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (tmp_i_nbreadreq_fu_64_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tx_ibhconnTable_req_blk_n = tx_ibhconnTable_req_empty_n;
    end else begin
        tx_ibhconnTable_req_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_64_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tx_ibhconnTable_req_read = 1'b1;
    end else begin
        tx_ibhconnTable_req_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((tmp_i_reg_230 == 1'd1) & (tx_connTable2ibh_rsp_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((tx_ibhconnTable_req_empty_n == 1'b0) & (tmp_i_nbreadreq_fu_64_p3 == 1'd1)) | ((ap_predicate_op17_read_state1 == 1'b1) & (s_axis_qp_conn_interface_TVALID_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((tmp_i_reg_230 == 1'd1) & (tx_connTable2ibh_rsp_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((tx_ibhconnTable_req_empty_n == 1'b0) & (tmp_i_nbreadreq_fu_64_p3 == 1'd1)) | ((ap_predicate_op17_read_state1 == 1'b1) & (s_axis_qp_conn_interface_TVALID_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((tmp_i_reg_230 == 1'd1) & (tx_connTable2ibh_rsp_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((tx_ibhconnTable_req_empty_n == 1'b0) & (tmp_i_nbreadreq_fu_64_p3 == 1'd1)) | ((ap_predicate_op17_read_state1 == 1'b1) & (s_axis_qp_conn_interface_TVALID_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((tx_ibhconnTable_req_empty_n == 1'b0) & (tmp_i_nbreadreq_fu_64_p3 == 1'd1)) | ((ap_predicate_op17_read_state1 == 1'b1) & (s_axis_qp_conn_interface_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((tmp_i_reg_230 == 1'd1) & (tx_connTable2ibh_rsp_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_117 = ((1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

always @ (*) begin
    ap_predicate_op17_read_state1 = ((tmp_i_267_nbreadreq_fu_72_p3 == 1'd1) & (tmp_i_nbreadreq_fu_64_p3 == 1'd0));
end

assign conn_table_remote_ip_address_V_d0 = {{s_axis_qp_conn_interface_TDATA_int_regslice[167:40]}};

assign conn_table_remote_qpn_V_d0 = {{s_axis_qp_conn_interface_TDATA_int_regslice[39:16]}};

assign conn_table_remote_udp_port_V_d0 = {{s_axis_qp_conn_interface_TDATA_int_regslice[183:168]}};

assign ifRequest_qpn_V_fu_162_p1 = s_axis_qp_conn_interface_TDATA_int_regslice[15:0];

assign s_axis_qp_conn_interface_TREADY = regslice_both_s_axis_qp_conn_interface_U_ack_in;

assign tmp_268_i_fu_213_p5 = {{{{conn_table_remote_udp_port_V_q0}, {conn_table_remote_ip_address_V_q0}}, {104'd0}}, {conn_table_remote_qpn_V_q0}};

assign tmp_i_267_nbreadreq_fu_72_p3 = s_axis_qp_conn_interface_TVALID_int_regslice;

assign tmp_i_nbreadreq_fu_64_p3 = tx_ibhconnTable_req_empty_n;

assign tx_connTable2ibh_rsp_din = tmp_268_i_fu_213_p5;

assign zext_ln541_7_fu_199_p1 = ifRequest_qpn_V_fu_162_p1;

assign zext_ln541_fu_206_p1 = tx_ibhconnTable_req_dout;

endmodule //rocev2_top_conn_table
