-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rocev2_top_generate_udp_64_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    tx_shift2udpFifo_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    tx_shift2udpFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    tx_shift2udpFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    tx_shift2udpFifo_empty_n : IN STD_LOGIC;
    tx_shift2udpFifo_read : OUT STD_LOGIC;
    tx_udpMetaFifo_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    tx_udpMetaFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    tx_udpMetaFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    tx_udpMetaFifo_empty_n : IN STD_LOGIC;
    tx_udpMetaFifo_read : OUT STD_LOGIC;
    tx_udp2ipFifo_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    tx_udp2ipFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    tx_udp2ipFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    tx_udp2ipFifo_full_n : IN STD_LOGIC;
    tx_udp2ipFifo_write : OUT STD_LOGIC );
end;


architecture behav of rocev2_top_generate_udp_64_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_1_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_1_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv128_lc_2 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001001000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv23_40 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000001000000";
    constant ap_const_lv23_41 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000001000001";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal state_4_load_load_fu_186_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_nbreadreq_fu_122_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op22_read_state1 : BOOLEAN;
    signal ap_predicate_op70_read_state1 : BOOLEAN;
    signal tmp_i_nbreadreq_fu_136_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op79_read_state1 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal state_4_load_reg_564 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_i_262_reg_575 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op100_write_state2 : BOOLEAN;
    signal tmp_194_i_reg_604 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op107_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal state_4 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal header_idx_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal header_header_V_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal tx_udpMetaFifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tx_udp2ipFifo_blk_n : STD_LOGIC;
    signal tx_shift2udpFifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal currWord_data_V_reg_568 : STD_LOGIC_VECTOR (63 downto 0);
    signal currWord_data_V_19_fu_200_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_reg_590 : STD_LOGIC_VECTOR (8 downto 0);
    signal tx_shift2udpFifo_read_reg_608 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_phi_reg_pp0_iter0_currWord_data_V_18_reg_157 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter1_currWord_data_V_18_reg_157 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln76_3_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln132_cast_i_fu_256_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln80_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln76_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_168_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_181_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_14_fu_512_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln130_fu_543_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln123_fu_559_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal shl_ln76_3_fu_204_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln76_3_fu_212_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln76_3_fu_216_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal xor_ln132_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_270_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln76_fu_278_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln76_fu_282_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal shl_ln8_fu_306_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln80_fu_314_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sub_ln80_fu_318_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln80_fu_324_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln80_5_fu_336_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln80_1_fu_342_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln80_6_fu_352_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_62_fu_328_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_63_fu_358_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_64_fu_368_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln80_fu_378_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln628_fu_420_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_195_i_fu_410_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_s_fu_424_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_198_i_fu_454_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_197_i9_fu_444_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_35_fu_432_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_36_fu_464_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_200_i_fu_494_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_199_i_fu_484_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_37_fu_472_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_38_fu_504_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_536_p3 : STD_LOGIC_VECTOR (72 downto 0);
    signal or_ln_fu_548_p3 : STD_LOGIC_VECTOR (64 downto 0);
    signal sext_ln123_fu_555_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_189 : BOOLEAN;
    signal ap_condition_193 : BOOLEAN;
    signal ap_condition_150 : BOOLEAN;
    signal ap_condition_221 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_currWord_data_V_18_reg_157_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nbreadreq_fu_122_p3 = ap_const_lv1_1) and (state_4 = ap_const_lv2_2) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (grp_fu_176_p2 = ap_const_lv1_0) and (icmp_ln76_3_fu_222_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                ap_phi_reg_pp0_iter1_currWord_data_V_18_reg_157 <= currWord_data_V_19_fu_200_p1;
            elsif ((((grp_nbreadreq_fu_122_p3 = ap_const_lv1_1) and (state_4 = ap_const_lv2_2) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (grp_fu_176_p2 = ap_const_lv1_1) and (icmp_ln76_3_fu_222_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((grp_nbreadreq_fu_122_p3 = ap_const_lv1_1) and (state_4 = ap_const_lv2_2) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln76_3_fu_222_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                ap_phi_reg_pp0_iter1_currWord_data_V_18_reg_157 <= header_header_V_3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                ap_phi_reg_pp0_iter1_currWord_data_V_18_reg_157 <= ap_phi_reg_pp0_iter0_currWord_data_V_18_reg_157;
            end if; 
        end if;
    end process;

    header_idx_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_nbreadreq_fu_136_p3 = ap_const_lv1_1) and (state_4 = ap_const_lv2_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                header_idx_3 <= ap_const_lv16_0;
            elsif (((state_4_load_load_fu_186_p1 = ap_const_lv2_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln76_fu_288_p2 = ap_const_lv1_0) and (grp_fu_176_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                header_idx_3 <= ap_const_lv16_1_2;
            elsif ((((grp_nbreadreq_fu_122_p3 = ap_const_lv1_1) and (state_4 = ap_const_lv2_2) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln76_3_fu_222_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((state_4_load_load_fu_186_p1 = ap_const_lv2_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln76_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                header_idx_3 <= grp_fu_181_p2;
            elsif (((grp_nbreadreq_fu_122_p3 = ap_const_lv1_1) and (state_4 = ap_const_lv2_2) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (grp_fu_176_p2 = ap_const_lv1_1) and (icmp_ln76_3_fu_222_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                header_idx_3 <= ap_const_lv16_1_1;
            end if; 
        end if;
    end process;

    state_4_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_150)) then
                if (((tmp_i_nbreadreq_fu_136_p3 = ap_const_lv1_1) and (state_4 = ap_const_lv2_0))) then 
                    state_4 <= ap_const_lv2_1;
                elsif ((ap_const_boolean_1 = ap_condition_193)) then 
                    state_4 <= ap_const_lv2_0;
                elsif ((ap_const_boolean_1 = ap_condition_189)) then 
                    state_4 <= ap_const_lv2_2;
                elsif (((grp_nbreadreq_fu_122_p3 = ap_const_lv1_1) and (state_4 = ap_const_lv2_2))) then 
                    state_4 <= select_ln132_cast_i_fu_256_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                currWord_data_V_reg_568 <= header_header_V_3;
                state_4_load_reg_564 <= state_4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_nbreadreq_fu_136_p3 = ap_const_lv1_1) and (state_4 = ap_const_lv2_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                header_header_V_3 <= p_Result_14_fu_512_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_4 = ap_const_lv2_3) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_194_i_reg_604 <= grp_nbreadreq_fu_122_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_4 = ap_const_lv2_2) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_i_262_reg_575 <= grp_nbreadreq_fu_122_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nbreadreq_fu_122_p3 = ap_const_lv1_1) and (state_4 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_reg_590 <= tx_shift2udpFifo_dout(72 downto 64);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_op70_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tx_shift2udpFifo_read_reg_608 <= tx_shift2udpFifo_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln76_3_fu_216_p2 <= std_logic_vector(unsigned(zext_ln76_3_fu_212_p1) + unsigned(ap_const_lv23_40));
    add_ln76_fu_282_p2 <= std_logic_vector(unsigned(zext_ln76_fu_278_p1) + unsigned(ap_const_lv23_40));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, tx_shift2udpFifo_empty_n, ap_predicate_op22_read_state1, ap_predicate_op70_read_state1, tx_udpMetaFifo_empty_n, ap_predicate_op79_read_state1, ap_done_reg, tx_udp2ipFifo_full_n, state_4_load_reg_564, ap_predicate_op100_write_state2, ap_predicate_op107_write_state2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op79_read_state1 = ap_const_boolean_1) and (tx_udpMetaFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op70_read_state1 = ap_const_boolean_1) and (tx_shift2udpFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_read_state1 = ap_const_boolean_1) and (tx_shift2udpFifo_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((state_4_load_reg_564 = ap_const_lv2_1) and (tx_udp2ipFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op100_write_state2 = ap_const_boolean_1) and (tx_udp2ipFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op107_write_state2 = ap_const_boolean_1) and (tx_udp2ipFifo_full_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, tx_shift2udpFifo_empty_n, ap_predicate_op22_read_state1, ap_predicate_op70_read_state1, tx_udpMetaFifo_empty_n, ap_predicate_op79_read_state1, ap_done_reg, tx_udp2ipFifo_full_n, state_4_load_reg_564, ap_predicate_op100_write_state2, ap_predicate_op107_write_state2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op79_read_state1 = ap_const_boolean_1) and (tx_udpMetaFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op70_read_state1 = ap_const_boolean_1) and (tx_shift2udpFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_read_state1 = ap_const_boolean_1) and (tx_shift2udpFifo_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((state_4_load_reg_564 = ap_const_lv2_1) and (tx_udp2ipFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op100_write_state2 = ap_const_boolean_1) and (tx_udp2ipFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op107_write_state2 = ap_const_boolean_1) and (tx_udp2ipFifo_full_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, tx_shift2udpFifo_empty_n, ap_predicate_op22_read_state1, ap_predicate_op70_read_state1, tx_udpMetaFifo_empty_n, ap_predicate_op79_read_state1, ap_done_reg, tx_udp2ipFifo_full_n, state_4_load_reg_564, ap_predicate_op100_write_state2, ap_predicate_op107_write_state2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op79_read_state1 = ap_const_boolean_1) and (tx_udpMetaFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op70_read_state1 = ap_const_boolean_1) and (tx_shift2udpFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_read_state1 = ap_const_boolean_1) and (tx_shift2udpFifo_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((state_4_load_reg_564 = ap_const_lv2_1) and (tx_udp2ipFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op100_write_state2 = ap_const_boolean_1) and (tx_udp2ipFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op107_write_state2 = ap_const_boolean_1) and (tx_udp2ipFifo_full_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(tx_shift2udpFifo_empty_n, ap_predicate_op22_read_state1, ap_predicate_op70_read_state1, tx_udpMetaFifo_empty_n, ap_predicate_op79_read_state1, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op79_read_state1 = ap_const_boolean_1) and (tx_udpMetaFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op70_read_state1 = ap_const_boolean_1) and (tx_shift2udpFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op22_read_state1 = ap_const_boolean_1) and (tx_shift2udpFifo_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(tx_udp2ipFifo_full_n, state_4_load_reg_564, ap_predicate_op100_write_state2, ap_predicate_op107_write_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((state_4_load_reg_564 = ap_const_lv2_1) and (tx_udp2ipFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op100_write_state2 = ap_const_boolean_1) and (tx_udp2ipFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op107_write_state2 = ap_const_boolean_1) and (tx_udp2ipFifo_full_n = ap_const_logic_0)));
    end process;


    ap_condition_150_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_150 <= ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_189_assign_proc : process(state_4_load_load_fu_186_p1, icmp_ln80_fu_386_p2, icmp_ln76_fu_288_p2)
    begin
                ap_condition_189 <= (((state_4_load_load_fu_186_p1 = ap_const_lv2_1) and (icmp_ln76_fu_288_p2 = ap_const_lv1_0)) or ((state_4_load_load_fu_186_p1 = ap_const_lv2_1) and (icmp_ln80_fu_386_p2 = ap_const_lv1_1)));
    end process;


    ap_condition_193_assign_proc : process(grp_nbreadreq_fu_122_p3, state_4, grp_fu_168_p3)
    begin
                ap_condition_193 <= ((grp_nbreadreq_fu_122_p3 = ap_const_lv1_1) and (state_4 = ap_const_lv2_3) and (grp_fu_168_p3 = ap_const_lv1_1));
    end process;


    ap_condition_221_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_221 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_currWord_data_V_18_reg_157 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op100_write_state2_assign_proc : process(state_4_load_reg_564, tmp_i_262_reg_575)
    begin
                ap_predicate_op100_write_state2 <= ((tmp_i_262_reg_575 = ap_const_lv1_1) and (state_4_load_reg_564 = ap_const_lv2_2));
    end process;


    ap_predicate_op107_write_state2_assign_proc : process(state_4_load_reg_564, tmp_194_i_reg_604)
    begin
                ap_predicate_op107_write_state2 <= ((tmp_194_i_reg_604 = ap_const_lv1_1) and (state_4_load_reg_564 = ap_const_lv2_3));
    end process;


    ap_predicate_op22_read_state1_assign_proc : process(grp_nbreadreq_fu_122_p3, state_4)
    begin
                ap_predicate_op22_read_state1 <= ((grp_nbreadreq_fu_122_p3 = ap_const_lv1_1) and (state_4 = ap_const_lv2_2));
    end process;


    ap_predicate_op70_read_state1_assign_proc : process(grp_nbreadreq_fu_122_p3, state_4)
    begin
                ap_predicate_op70_read_state1 <= ((grp_nbreadreq_fu_122_p3 = ap_const_lv1_1) and (state_4 = ap_const_lv2_3));
    end process;


    ap_predicate_op79_read_state1_assign_proc : process(tmp_i_nbreadreq_fu_136_p3, state_4)
    begin
                ap_predicate_op79_read_state1 <= ((tmp_i_nbreadreq_fu_136_p3 = ap_const_lv1_1) and (state_4 = ap_const_lv2_0));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    currWord_data_V_19_fu_200_p1 <= tx_shift2udpFifo_dout(64 - 1 downto 0);
    grp_fu_168_p3 <= tx_shift2udpFifo_dout(72 downto 72);
    grp_fu_176_p2 <= "1" when (header_idx_3 = ap_const_lv16_0) else "0";
    grp_fu_181_p2 <= std_logic_vector(unsigned(header_idx_3) + unsigned(ap_const_lv16_1));
    grp_nbreadreq_fu_122_p3 <= (0=>(tx_shift2udpFifo_empty_n), others=>'-');
    icmp_ln76_3_fu_222_p2 <= "1" when (unsigned(add_ln76_3_fu_216_p2) < unsigned(ap_const_lv23_41)) else "0";
    icmp_ln76_fu_288_p2 <= "1" when (unsigned(add_ln76_fu_282_p2) < unsigned(ap_const_lv23_41)) else "0";
    icmp_ln80_fu_386_p2 <= "1" when (select_ln80_fu_378_p3 = ap_const_lv5_0) else "0";
    or_ln_fu_548_p3 <= (ap_const_lv1_1 & currWord_data_V_reg_568);
    p_Result_14_fu_512_p5 <= (p_Result_37_fu_472_p5(63 downto 48) & p_Result_38_fu_504_p3 & p_Result_37_fu_472_p5(31 downto 0));
    p_Result_35_fu_432_p5 <= (header_header_V_3(63 downto 32) & p_Result_s_fu_424_p3 & header_header_V_3(15 downto 0));
    p_Result_36_fu_464_p3 <= (tmp_198_i_fu_454_p4 & tmp_197_i9_fu_444_p4);
    p_Result_37_fu_472_p5 <= (p_Result_35_fu_432_p5(63 downto 16) & p_Result_36_fu_464_p3);
    p_Result_38_fu_504_p3 <= (tmp_200_i_fu_494_p4 & tmp_199_i_fu_484_p4);
    p_Result_s_fu_424_p3 <= (trunc_ln628_fu_420_p1 & tmp_195_i_fu_410_p4);
    select_ln132_cast_i_fu_256_p3 <= 
        ap_const_lv2_3 when (xor_ln132_fu_250_p2(0) = '1') else 
        ap_const_lv2_0;
    select_ln80_fu_378_p3 <= 
        tmp_63_fu_358_p4 when (tmp_62_fu_328_p3(0) = '1') else 
        tmp_64_fu_368_p4;
        sext_ln123_fu_555_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln_fu_548_p3),72));

    shl_ln76_3_fu_204_p3 <= (header_idx_3 & ap_const_lv6_0);
    shl_ln8_fu_306_p3 <= (grp_fu_181_p2 & ap_const_lv6_0);
    shl_ln_fu_270_p3 <= (header_idx_3 & ap_const_lv6_0);
    state_4_load_load_fu_186_p1 <= state_4;
    sub_ln80_5_fu_336_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(trunc_ln80_fu_324_p1));
    sub_ln80_6_fu_352_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(trunc_ln80_1_fu_342_p4));
    sub_ln80_fu_318_p2 <= std_logic_vector(unsigned(ap_const_lv23_40) - unsigned(zext_ln80_fu_314_p1));
    tmp_195_i_fu_410_p4 <= tx_udpMetaFifo_dout(15 downto 8);
    tmp_197_i9_fu_444_p4 <= tx_udpMetaFifo_dout(31 downto 24);
    tmp_198_i_fu_454_p4 <= tx_udpMetaFifo_dout(23 downto 16);
    tmp_199_i_fu_484_p4 <= tx_udpMetaFifo_dout(47 downto 40);
    tmp_200_i_fu_494_p4 <= tx_udpMetaFifo_dout(39 downto 32);
    tmp_62_fu_328_p3 <= sub_ln80_fu_318_p2(22 downto 22);
    tmp_63_fu_358_p4 <= sub_ln80_6_fu_352_p2(7 downto 3);
    tmp_64_fu_368_p4 <= sub_ln80_fu_318_p2(10 downto 6);
    tmp_i_nbreadreq_fu_136_p3 <= (0=>(tx_udpMetaFifo_empty_n), others=>'-');
    tmp_s_fu_536_p3 <= (tmp_reg_590 & ap_phi_reg_pp0_iter1_currWord_data_V_18_reg_157);
    trunc_ln628_fu_420_p1 <= tx_udpMetaFifo_dout(8 - 1 downto 0);
    trunc_ln80_1_fu_342_p4 <= sub_ln80_5_fu_336_p2(10 downto 3);
    trunc_ln80_fu_324_p1 <= sub_ln80_fu_318_p2(11 - 1 downto 0);

    tx_shift2udpFifo_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tx_shift2udpFifo_empty_n, ap_predicate_op22_read_state1, ap_predicate_op70_read_state1, ap_done_reg, ap_block_pp0_stage0)
    begin
        if ((((ap_done_reg = ap_const_logic_0) and (ap_predicate_op70_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_done_reg = ap_const_logic_0) and (ap_predicate_op22_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            tx_shift2udpFifo_blk_n <= tx_shift2udpFifo_empty_n;
        else 
            tx_shift2udpFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    tx_shift2udpFifo_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op22_read_state1, ap_predicate_op70_read_state1, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_predicate_op70_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op22_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            tx_shift2udpFifo_read <= ap_const_logic_1;
        else 
            tx_shift2udpFifo_read <= ap_const_logic_0;
        end if; 
    end process;


    tx_udp2ipFifo_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tx_udp2ipFifo_full_n, state_4_load_reg_564, ap_predicate_op100_write_state2, ap_predicate_op107_write_state2, ap_block_pp0_stage0)
    begin
        if ((((state_4_load_reg_564 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_predicate_op100_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_predicate_op107_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            tx_udp2ipFifo_blk_n <= tx_udp2ipFifo_full_n;
        else 
            tx_udp2ipFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    tx_udp2ipFifo_din_assign_proc : process(state_4_load_reg_564, ap_predicate_op100_write_state2, ap_predicate_op107_write_state2, tx_shift2udpFifo_read_reg_608, zext_ln130_fu_543_p1, zext_ln123_fu_559_p1, ap_condition_221)
    begin
        if ((ap_const_boolean_1 = ap_condition_221)) then
            if ((ap_predicate_op107_write_state2 = ap_const_boolean_1)) then 
                tx_udp2ipFifo_din <= tx_shift2udpFifo_read_reg_608;
            elsif ((state_4_load_reg_564 = ap_const_lv2_1)) then 
                tx_udp2ipFifo_din <= zext_ln123_fu_559_p1;
            elsif ((ap_predicate_op100_write_state2 = ap_const_boolean_1)) then 
                tx_udp2ipFifo_din <= zext_ln130_fu_543_p1;
            else 
                tx_udp2ipFifo_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            tx_udp2ipFifo_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    tx_udp2ipFifo_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_4_load_reg_564, ap_predicate_op100_write_state2, ap_predicate_op107_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((state_4_load_reg_564 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op100_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op107_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            tx_udp2ipFifo_write <= ap_const_logic_1;
        else 
            tx_udp2ipFifo_write <= ap_const_logic_0;
        end if; 
    end process;


    tx_udpMetaFifo_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tx_udpMetaFifo_empty_n, ap_predicate_op79_read_state1, ap_done_reg, ap_block_pp0_stage0)
    begin
        if (((ap_done_reg = ap_const_logic_0) and (ap_predicate_op79_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            tx_udpMetaFifo_blk_n <= tx_udpMetaFifo_empty_n;
        else 
            tx_udpMetaFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    tx_udpMetaFifo_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op79_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op79_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            tx_udpMetaFifo_read <= ap_const_logic_1;
        else 
            tx_udpMetaFifo_read <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln132_fu_250_p2 <= (grp_fu_168_p3 xor ap_const_lv1_1);
    zext_ln123_fu_559_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln123_fu_555_p1),128));
    zext_ln130_fu_543_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_536_p3),128));
    zext_ln76_3_fu_212_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln76_3_fu_204_p3),23));
    zext_ln76_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_270_p3),23));
    zext_ln80_fu_314_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln8_fu_306_p3),23));
end behav;
