-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rocev2_top_extract_icrc_64_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_axis_rx_data_TVALID : IN STD_LOGIC;
    rx_crc2ipFifo_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    rx_crc2ipFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_crc2ipFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_crc2ipFifo_full_n : IN STD_LOGIC;
    rx_crc2ipFifo_write : OUT STD_LOGIC;
    s_axis_rx_data_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    s_axis_rx_data_TREADY : OUT STD_LOGIC );
end;


architecture behav of rocev2_top_extract_icrc_64_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_F : STD_LOGIC_VECTOR (7 downto 0) := "00001111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv128_lc_2 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001001000";
    constant ap_const_lv32_44 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000100";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal grp_nbreadreq_fu_68_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op16_read_state1 : BOOLEAN;
    signal ap_predicate_op38_read_state1 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ei_state_load_reg_313 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_i_265_reg_335 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op55_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ei_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ei_prevWord_data_V : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ei_prevWord_keep_V : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ei_prevWord_last_V : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal s_axis_rx_data_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal rx_crc2ipFifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ei_prevWord_data_V_load_reg_317 : STD_LOGIC_VECTOR (63 downto 0);
    signal ei_prevWord_keep_V_load_reg_323 : STD_LOGIC_VECTOR (7 downto 0);
    signal ei_prevWord_last_V_load_reg_329 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln73_fu_201_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_157_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_ei_prevWord_last_V_flag_2_i_phi_fu_92_p10 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_ei_prevWord_last_V_flag_2_i_reg_89 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_ei_prevWord_last_V_new_2_i_phi_fu_112_p10 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_ei_prevWord_last_V_new_2_i_reg_109 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_ei_prevWord_last_V_loc_1_i_reg_127 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_ei_prevWord_last_V_loc_1_i_reg_127 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_void_extract_icrc_64_hls_stream_net_axis_64_0_hls_stream_net_axis_64_0_ei_prevWord_reg_136 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_void_extract_icrc_64_hls_stream_net_axis_64_0_hls_stream_net_axis_64_0_ei_prevWord_reg_136 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln93_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln73_fu_207_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln61_fu_267_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal currWord_data_V_20_fu_183_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal currWord_data_V_fu_251_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln87_fu_295_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln160_fu_308_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_fu_187_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_195_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_267_i_fu_287_p4 : STD_LOGIC_VECTOR (72 downto 0);
    signal tmp_266_i_fu_300_p4 : STD_LOGIC_VECTOR (72 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_s_axis_rx_data_U_apdone_blk : STD_LOGIC;
    signal s_axis_rx_data_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal s_axis_rx_data_TVALID_int_regslice : STD_LOGIC;
    signal s_axis_rx_data_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_axis_rx_data_U_ack_in : STD_LOGIC;
    signal ap_condition_139 : BOOLEAN;
    signal ap_condition_165 : BOOLEAN;
    signal ap_condition_133 : BOOLEAN;
    signal ap_condition_309 : BOOLEAN;
    signal ap_condition_47 : BOOLEAN;
    signal ap_condition_198 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component rocev2_top_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_s_axis_rx_data_U : component rocev2_top_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_axis_rx_data_TDATA,
        vld_in => s_axis_rx_data_TVALID,
        ack_in => regslice_both_s_axis_rx_data_U_ack_in,
        data_out => s_axis_rx_data_TDATA_int_regslice,
        vld_out => s_axis_rx_data_TVALID_int_regslice,
        ack_out => s_axis_rx_data_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_rx_data_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_ei_prevWord_last_V_loc_1_i_reg_127_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_133)) then
                if ((ap_const_boolean_1 = ap_condition_165)) then 
                    ap_phi_reg_pp0_iter1_ei_prevWord_last_V_loc_1_i_reg_127 <= ei_prevWord_last_V;
                elsif ((ap_const_boolean_1 = ap_condition_139)) then 
                    ap_phi_reg_pp0_iter1_ei_prevWord_last_V_loc_1_i_reg_127 <= or_ln73_fu_201_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_ei_prevWord_last_V_loc_1_i_reg_127 <= ap_phi_reg_pp0_iter0_ei_prevWord_last_V_loc_1_i_reg_127;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_void_extract_icrc_64_hls_stream_net_axis_64_0_hls_stream_net_axis_64_0_ei_prevWord_reg_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_133)) then
                if (((ei_state = ap_const_lv2_2) and (icmp_ln93_fu_233_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_void_extract_icrc_64_hls_stream_net_axis_64_0_hls_stream_net_axis_64_0_ei_prevWord_reg_136 <= ei_prevWord_keep_V;
                elsif (((ei_state = ap_const_lv2_2) and (icmp_ln93_fu_233_p2 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_void_extract_icrc_64_hls_stream_net_axis_64_0_hls_stream_net_axis_64_0_ei_prevWord_reg_136 <= ap_const_lv8_F;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_void_extract_icrc_64_hls_stream_net_axis_64_0_hls_stream_net_axis_64_0_ei_prevWord_reg_136 <= ap_phi_reg_pp0_iter0_void_extract_icrc_64_hls_stream_net_axis_64_0_hls_stream_net_axis_64_0_ei_prevWord_reg_136;
                end if;
            end if; 
        end if;
    end process;

    ei_prevWord_data_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_309)) then
                if ((not((ei_state = ap_const_lv2_2)) and not((ei_state = ap_const_lv2_1)))) then 
                    ei_prevWord_data_V <= currWord_data_V_fu_251_p1;
                elsif ((ei_state = ap_const_lv2_1)) then 
                    ei_prevWord_data_V <= currWord_data_V_20_fu_183_p1;
                end if;
            end if; 
        end if;
    end process;

    ei_prevWord_keep_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ei_state = ap_const_lv2_2) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln93_fu_233_p2 = ap_const_lv1_1))) then 
                ei_prevWord_keep_V <= ap_const_lv8_F;
            elsif (((not((ei_state = ap_const_lv2_2)) and not((ei_state = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (grp_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (grp_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (ei_state = ap_const_lv2_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                ei_prevWord_keep_V <= s_axis_rx_data_TDATA_int_regslice(71 downto 64);
            end if; 
        end if;
    end process;

    ei_state_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_133)) then
                if ((ap_const_boolean_1 = ap_condition_47)) then 
                    ei_state <= select_ln61_fu_267_p3;
                elsif ((ei_state = ap_const_lv2_2)) then 
                    ei_state <= ap_const_lv2_0;
                elsif ((ap_const_boolean_1 = ap_condition_139)) then 
                    ei_state <= select_ln73_fu_207_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ei_prevWord_data_V_load_reg_317 <= ei_prevWord_data_V;
                ei_prevWord_keep_V_load_reg_323 <= ei_prevWord_keep_V;
                ei_prevWord_last_V_load_reg_329 <= ei_prevWord_last_V;
                ei_state_load_reg_313 <= ei_state;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_ei_prevWord_last_V_flag_2_i_phi_fu_92_p10 = ap_const_lv1_1))) then
                ei_prevWord_last_V <= ap_phi_mux_ei_prevWord_last_V_new_2_i_phi_fu_112_p10;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ei_state = ap_const_lv2_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_i_265_reg_335 <= grp_nbreadreq_fu_68_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, ap_predicate_op16_read_state1, ap_predicate_op38_read_state1, ap_done_reg, rx_crc2ipFifo_full_n, ei_state_load_reg_313, ap_predicate_op55_write_state2, s_axis_rx_data_TVALID_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ei_state_load_reg_313 = ap_const_lv2_2) and (rx_crc2ipFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op55_write_state2 = ap_const_boolean_1) and (rx_crc2ipFifo_full_n = ap_const_logic_0)))) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op38_read_state1 = ap_const_boolean_1) and (s_axis_rx_data_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (s_axis_rx_data_TVALID_int_regslice = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, ap_predicate_op16_read_state1, ap_predicate_op38_read_state1, ap_done_reg, rx_crc2ipFifo_full_n, ei_state_load_reg_313, ap_predicate_op55_write_state2, s_axis_rx_data_TVALID_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ei_state_load_reg_313 = ap_const_lv2_2) and (rx_crc2ipFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op55_write_state2 = ap_const_boolean_1) and (rx_crc2ipFifo_full_n = ap_const_logic_0)))) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op38_read_state1 = ap_const_boolean_1) and (s_axis_rx_data_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (s_axis_rx_data_TVALID_int_regslice = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, ap_predicate_op16_read_state1, ap_predicate_op38_read_state1, ap_done_reg, rx_crc2ipFifo_full_n, ei_state_load_reg_313, ap_predicate_op55_write_state2, s_axis_rx_data_TVALID_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ei_state_load_reg_313 = ap_const_lv2_2) and (rx_crc2ipFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op55_write_state2 = ap_const_boolean_1) and (rx_crc2ipFifo_full_n = ap_const_logic_0)))) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op38_read_state1 = ap_const_boolean_1) and (s_axis_rx_data_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (s_axis_rx_data_TVALID_int_regslice = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_predicate_op16_read_state1, ap_predicate_op38_read_state1, ap_done_reg, s_axis_rx_data_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op38_read_state1 = ap_const_boolean_1) and (s_axis_rx_data_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (s_axis_rx_data_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(rx_crc2ipFifo_full_n, ei_state_load_reg_313, ap_predicate_op55_write_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((ei_state_load_reg_313 = ap_const_lv2_2) and (rx_crc2ipFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op55_write_state2 = ap_const_boolean_1) and (rx_crc2ipFifo_full_n = ap_const_logic_0)));
    end process;


    ap_condition_133_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_133 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_139_assign_proc : process(grp_nbreadreq_fu_68_p3, ei_state, grp_fu_157_p3)
    begin
                ap_condition_139 <= ((grp_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (ei_state = ap_const_lv2_1) and (grp_fu_157_p3 = ap_const_lv1_1));
    end process;


    ap_condition_165_assign_proc : process(grp_nbreadreq_fu_68_p3, ei_state, grp_fu_157_p3)
    begin
                ap_condition_165 <= ((grp_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (ei_state = ap_const_lv2_1) and (grp_fu_157_p3 = ap_const_lv1_0));
    end process;


    ap_condition_198_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_198 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_309_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, grp_nbreadreq_fu_68_p3, ap_block_pp0_stage0_11001)
    begin
                ap_condition_309 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (grp_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_47_assign_proc : process(grp_nbreadreq_fu_68_p3, ei_state)
    begin
                ap_condition_47 <= (not((ei_state = ap_const_lv2_2)) and not((ei_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_68_p3 = ap_const_lv1_1));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_ei_prevWord_last_V_flag_2_i_phi_fu_92_p10_assign_proc : process(grp_nbreadreq_fu_68_p3, ei_state, ap_phi_reg_pp0_iter0_ei_prevWord_last_V_flag_2_i_reg_89)
    begin
        if (((ei_state = ap_const_lv2_2) or (not((ei_state = ap_const_lv2_2)) and not((ei_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_68_p3 = ap_const_lv1_0)) or ((grp_nbreadreq_fu_68_p3 = ap_const_lv1_0) and (ei_state = ap_const_lv2_1)))) then 
            ap_phi_mux_ei_prevWord_last_V_flag_2_i_phi_fu_92_p10 <= ap_const_lv1_0;
        elsif (((not((ei_state = ap_const_lv2_2)) and not((ei_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_68_p3 = ap_const_lv1_1)) or ((grp_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (ei_state = ap_const_lv2_1)))) then 
            ap_phi_mux_ei_prevWord_last_V_flag_2_i_phi_fu_92_p10 <= ap_const_lv1_1;
        else 
            ap_phi_mux_ei_prevWord_last_V_flag_2_i_phi_fu_92_p10 <= ap_phi_reg_pp0_iter0_ei_prevWord_last_V_flag_2_i_reg_89;
        end if; 
    end process;


    ap_phi_mux_ei_prevWord_last_V_new_2_i_phi_fu_112_p10_assign_proc : process(grp_nbreadreq_fu_68_p3, ei_state, ap_phi_reg_pp0_iter0_ei_prevWord_last_V_new_2_i_reg_109, s_axis_rx_data_TDATA_int_regslice)
    begin
        if (((not((ei_state = ap_const_lv2_2)) and not((ei_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_68_p3 = ap_const_lv1_1)) or ((grp_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (ei_state = ap_const_lv2_1)))) then 
            ap_phi_mux_ei_prevWord_last_V_new_2_i_phi_fu_112_p10 <= s_axis_rx_data_TDATA_int_regslice(72 downto 72);
        else 
            ap_phi_mux_ei_prevWord_last_V_new_2_i_phi_fu_112_p10 <= ap_phi_reg_pp0_iter0_ei_prevWord_last_V_new_2_i_reg_109;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_ei_prevWord_last_V_flag_2_i_reg_89 <= "X";
    ap_phi_reg_pp0_iter0_ei_prevWord_last_V_loc_1_i_reg_127 <= "X";
    ap_phi_reg_pp0_iter0_ei_prevWord_last_V_new_2_i_reg_109 <= "X";
    ap_phi_reg_pp0_iter0_void_extract_icrc_64_hls_stream_net_axis_64_0_hls_stream_net_axis_64_0_ei_prevWord_reg_136 <= "XXXXXXXX";

    ap_predicate_op16_read_state1_assign_proc : process(grp_nbreadreq_fu_68_p3, ei_state)
    begin
                ap_predicate_op16_read_state1 <= ((grp_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (ei_state = ap_const_lv2_1));
    end process;


    ap_predicate_op38_read_state1_assign_proc : process(grp_nbreadreq_fu_68_p3, ei_state)
    begin
                ap_predicate_op38_read_state1 <= (not((ei_state = ap_const_lv2_2)) and not((ei_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_68_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op55_write_state2_assign_proc : process(ei_state_load_reg_313, tmp_i_265_reg_335)
    begin
                ap_predicate_op55_write_state2 <= ((tmp_i_265_reg_335 = ap_const_lv1_1) and (ei_state_load_reg_313 = ap_const_lv2_1));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    currWord_data_V_20_fu_183_p1 <= s_axis_rx_data_TDATA_int_regslice(64 - 1 downto 0);
    currWord_data_V_fu_251_p1 <= s_axis_rx_data_TDATA_int_regslice(64 - 1 downto 0);
    grp_fu_157_p3 <= s_axis_rx_data_TDATA_int_regslice(72 downto 72);
    grp_nbreadreq_fu_68_p3 <= (0=>(s_axis_rx_data_TVALID_int_regslice), others=>'-');
    icmp_ln93_fu_233_p2 <= "1" when (ei_prevWord_keep_V = ap_const_lv8_FF) else "0";
    or_ln73_fu_201_p2 <= (p_Result_s_fu_195_p2 or ei_prevWord_last_V);
    p_Result_s_fu_195_p2 <= (tmp_fu_187_p3 xor ap_const_lv1_1);

    rx_crc2ipFifo_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rx_crc2ipFifo_full_n, ei_state_load_reg_313, ap_predicate_op55_write_state2, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ei_state_load_reg_313 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op55_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            rx_crc2ipFifo_blk_n <= rx_crc2ipFifo_full_n;
        else 
            rx_crc2ipFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_crc2ipFifo_din_assign_proc : process(ei_state_load_reg_313, ap_predicate_op55_write_state2, zext_ln87_fu_295_p1, zext_ln160_fu_308_p1, ap_condition_198)
    begin
        if ((ap_const_boolean_1 = ap_condition_198)) then
            if ((ei_state_load_reg_313 = ap_const_lv2_2)) then 
                rx_crc2ipFifo_din <= zext_ln160_fu_308_p1;
            elsif ((ap_predicate_op55_write_state2 = ap_const_boolean_1)) then 
                rx_crc2ipFifo_din <= zext_ln87_fu_295_p1;
            else 
                rx_crc2ipFifo_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            rx_crc2ipFifo_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    rx_crc2ipFifo_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ei_state_load_reg_313, ap_predicate_op55_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ei_state_load_reg_313 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op55_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            rx_crc2ipFifo_write <= ap_const_logic_1;
        else 
            rx_crc2ipFifo_write <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_rx_data_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op16_read_state1, ap_predicate_op38_read_state1, ap_done_reg, ap_block_pp0_stage0, s_axis_rx_data_TVALID_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_done_reg = ap_const_logic_0) and (ap_predicate_op38_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_done_reg = ap_const_logic_0) and (ap_predicate_op16_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            s_axis_rx_data_TDATA_blk_n <= s_axis_rx_data_TVALID_int_regslice;
        else 
            s_axis_rx_data_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_axis_rx_data_TREADY <= regslice_both_s_axis_rx_data_U_ack_in;

    s_axis_rx_data_TREADY_int_regslice_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op16_read_state1, ap_predicate_op38_read_state1, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op38_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op16_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            s_axis_rx_data_TREADY_int_regslice <= ap_const_logic_1;
        else 
            s_axis_rx_data_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    select_ln61_fu_267_p3 <= 
        ap_const_lv2_2 when (grp_fu_157_p3(0) = '1') else 
        ap_const_lv2_1;
    select_ln73_fu_207_p3 <= 
        ap_const_lv2_2 when (tmp_fu_187_p3(0) = '1') else 
        ap_const_lv2_0;
    tmp_266_i_fu_300_p4 <= ((ei_prevWord_last_V_load_reg_329 & ap_phi_reg_pp0_iter1_void_extract_icrc_64_hls_stream_net_axis_64_0_hls_stream_net_axis_64_0_ei_prevWord_reg_136) & ei_prevWord_data_V_load_reg_317);
    tmp_267_i_fu_287_p4 <= ((ap_phi_reg_pp0_iter1_ei_prevWord_last_V_loc_1_i_reg_127 & ei_prevWord_keep_V_load_reg_323) & ei_prevWord_data_V_load_reg_317);
    tmp_fu_187_p3 <= s_axis_rx_data_TDATA_int_regslice(68 downto 68);
    zext_ln160_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_266_i_fu_300_p4),128));
    zext_ln87_fu_295_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_267_i_fu_287_p4),128));
end behav;
