-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rocev2_top_ipv4_generate_ipv4_64_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    local_ip_address_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    local_ip_address_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    local_ip_address_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    local_ip_address_empty_n : IN STD_LOGIC;
    local_ip_address_read : OUT STD_LOGIC;
    tx_shift2ipv4Fifo_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    tx_shift2ipv4Fifo_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    tx_shift2ipv4Fifo_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    tx_shift2ipv4Fifo_empty_n : IN STD_LOGIC;
    tx_shift2ipv4Fifo_read : OUT STD_LOGIC;
    tx_udp2ipMetaFifo_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    tx_udp2ipMetaFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    tx_udp2ipMetaFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    tx_udp2ipMetaFifo_empty_n : IN STD_LOGIC;
    tx_udp2ipMetaFifo_read : OUT STD_LOGIC;
    tx_ip2crcFifo_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    tx_ip2crcFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    tx_ip2crcFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    tx_ip2crcFifo_full_n : IN STD_LOGIC;
    tx_ip2crcFifo_write : OUT STD_LOGIC );
end;


architecture behav of rocev2_top_ipv4_generate_ipv4_64_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv128_lc_2 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001001000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv23_40 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000001000000";
    constant ap_const_lv23_A1 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000010100001";
    constant ap_const_lv22_A0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000010100000";
    constant ap_const_lv160_lc_3 : STD_LOGIC_VECTOR (159 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv23_A0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000010100000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv16_14 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv8_11 : STD_LOGIC_VECTOR (7 downto 0) := "00010001";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal gi_state_load_load_fu_253_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_nbreadreq_fu_164_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op25_read_state1 : BOOLEAN;
    signal ap_predicate_op105_read_state1 : BOOLEAN;
    signal tmp_i_i_nbreadreq_fu_178_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op114_read_state1 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal gi_state_load_reg_780 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_i_i_259_reg_784 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op133_write_state2 : BOOLEAN;
    signal tmp_177_i_i_reg_830 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op141_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal gi_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal header_idx_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal header_header_V_2 : STD_LOGIC_VECTOR (159 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000101";
    signal local_ip_address_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tx_udp2ipMetaFifo_blk_n : STD_LOGIC;
    signal tx_ip2crcFifo_blk_n : STD_LOGIC;
    signal tx_shift2ipv4Fifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal currWord_data_V_14_fu_266_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_30_fu_346_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln76_2_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln82_2_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal currWord_data_V_11_fu_382_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_reg_809 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_28_fu_498_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln76_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln82_fu_454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal currWord_data_V_fu_534_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tx_shift2ipv4Fifo_read_reg_834 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_phi_mux_phi_ln1027_phi_fu_202_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_phi_ln1027_reg_199 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_currWord_data_V_13_reg_212 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter1_currWord_data_V_13_reg_212 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter0_currWord_data_V_10_reg_223 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter1_currWord_data_V_10_reg_223 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln222_cast_i_i_fu_408_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_236_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_244_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_13_fu_727_p5 : STD_LOGIC_VECTOR (159 downto 0);
    signal zext_ln219_fu_758_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln210_fu_775_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal shl_ln76_2_fu_278_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln76_2_fu_286_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln76_2_fu_290_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln76_6_fu_274_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_53_fu_308_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln628_9_fu_316_p1 : STD_LOGIC_VECTOR (159 downto 0);
    signal zext_ln628_10_fu_320_p1 : STD_LOGIC_VECTOR (159 downto 0);
    signal lshr_ln628_9_fu_324_p2 : STD_LOGIC_VECTOR (159 downto 0);
    signal lshr_ln628_10_fu_330_p2 : STD_LOGIC_VECTOR (159 downto 0);
    signal p_Result_29_fu_336_p2 : STD_LOGIC_VECTOR (159 downto 0);
    signal trunc_ln368_2_fu_342_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln76_5_fu_270_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_52_fu_364_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln628_8_fu_372_p1 : STD_LOGIC_VECTOR (159 downto 0);
    signal lshr_ln628_8_fu_376_p2 : STD_LOGIC_VECTOR (159 downto 0);
    signal xor_ln222_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_430_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln76_fu_438_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln76_fu_442_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln76_4_fu_426_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_51_fu_460_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln628_6_fu_468_p1 : STD_LOGIC_VECTOR (159 downto 0);
    signal zext_ln628_7_fu_472_p1 : STD_LOGIC_VECTOR (159 downto 0);
    signal lshr_ln628_6_fu_476_p2 : STD_LOGIC_VECTOR (159 downto 0);
    signal lshr_ln628_7_fu_482_p2 : STD_LOGIC_VECTOR (159 downto 0);
    signal p_Result_27_fu_488_p2 : STD_LOGIC_VECTOR (159 downto 0);
    signal trunc_ln368_fu_494_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln76_fu_422_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_46_fu_516_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln628_fu_524_p1 : STD_LOGIC_VECTOR (159 downto 0);
    signal lshr_ln628_fu_528_p2 : STD_LOGIC_VECTOR (159 downto 0);
    signal shl_ln7_fu_544_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln80_fu_552_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sub_ln80_fu_556_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln80_fu_562_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln80_3_fu_574_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln80_8_fu_580_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln80_4_fu_590_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_47_fu_566_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_48_fu_596_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_49_fu_606_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln80_fu_616_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal meta_length_V_2_fu_647_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal len_V_fu_663_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln628_fu_679_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_178_i_i9_fu_669_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_s_fu_683_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_24_fu_691_p5 : STD_LOGIC_VECTOR (159 downto 0);
    signal meta_their_address_V_fu_643_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_25_fu_703_p5 : STD_LOGIC_VECTOR (159 downto 0);
    signal trunc_ln186_fu_249_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_26_fu_715_p5 : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_fu_751_p3 : STD_LOGIC_VECTOR (72 downto 0);
    signal or_ln_fu_763_p3 : STD_LOGIC_VECTOR (64 downto 0);
    signal sext_ln210_fu_771_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_192 : BOOLEAN;
    signal ap_condition_162 : BOOLEAN;
    signal ap_condition_180 : BOOLEAN;
    signal ap_condition_175 : BOOLEAN;
    signal ap_condition_220 : BOOLEAN;
    signal ap_condition_232 : BOOLEAN;
    signal ap_condition_256 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_currWord_data_V_10_reg_223_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_162)) then
                if ((ap_const_boolean_1 = ap_condition_192)) then 
                    ap_phi_reg_pp0_iter1_currWord_data_V_10_reg_223 <= p_Result_28_fu_498_p5;
                elsif (((gi_state_load_load_fu_253_p1 = ap_const_lv2_1) and (icmp_ln76_fu_448_p2 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_currWord_data_V_10_reg_223 <= currWord_data_V_fu_534_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_currWord_data_V_10_reg_223 <= ap_phi_reg_pp0_iter0_currWord_data_V_10_reg_223;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_currWord_data_V_13_reg_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_162)) then
                if ((ap_const_boolean_1 = ap_condition_220)) then 
                    ap_phi_reg_pp0_iter1_currWord_data_V_13_reg_212 <= currWord_data_V_14_fu_266_p1;
                elsif ((ap_const_boolean_1 = ap_condition_175)) then 
                    ap_phi_reg_pp0_iter1_currWord_data_V_13_reg_212 <= p_Result_30_fu_346_p5;
                elsif ((ap_const_boolean_1 = ap_condition_180)) then 
                    ap_phi_reg_pp0_iter1_currWord_data_V_13_reg_212 <= currWord_data_V_11_fu_382_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_currWord_data_V_13_reg_212 <= ap_phi_reg_pp0_iter0_currWord_data_V_13_reg_212;
                end if;
            end if; 
        end if;
    end process;

    gi_state_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_162)) then
                if (((tmp_i_i_nbreadreq_fu_178_p3 = ap_const_lv1_1) and (gi_state = ap_const_lv2_0))) then 
                    gi_state <= ap_const_lv2_1;
                elsif ((ap_const_boolean_1 = ap_condition_232)) then 
                    gi_state <= ap_const_lv2_0;
                elsif (((gi_state_load_load_fu_253_p1 = ap_const_lv2_1) and (ap_phi_mux_phi_ln1027_phi_fu_202_p6 = ap_const_lv1_1))) then 
                    gi_state <= ap_const_lv2_2;
                elsif (((grp_nbreadreq_fu_164_p3 = ap_const_lv1_1) and (gi_state = ap_const_lv2_2))) then 
                    gi_state <= select_ln222_cast_i_i_fu_408_p3;
                end if;
            end if; 
        end if;
    end process;

    header_idx_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_i_nbreadreq_fu_178_p3 = ap_const_lv1_1) and (gi_state = ap_const_lv2_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                header_idx_2 <= ap_const_lv16_0;
            elsif ((((grp_nbreadreq_fu_164_p3 = ap_const_lv1_1) and (gi_state = ap_const_lv2_2) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln76_2_fu_296_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((grp_nbreadreq_fu_164_p3 = ap_const_lv1_1) and (gi_state = ap_const_lv2_2) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln82_2_fu_302_p2 = ap_const_lv1_1) and (icmp_ln76_2_fu_296_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((gi_state_load_load_fu_253_p1 = ap_const_lv2_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln76_fu_448_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((gi_state_load_load_fu_253_p1 = ap_const_lv2_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln82_fu_454_p2 = ap_const_lv1_1) and (icmp_ln76_fu_448_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                header_idx_2 <= grp_fu_244_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                gi_state_load_reg_780 <= gi_state;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_i_nbreadreq_fu_178_p3 = ap_const_lv1_1) and (gi_state = ap_const_lv2_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                header_header_V_2 <= p_Result_13_fu_727_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((gi_state = ap_const_lv2_3) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_177_i_i_reg_830 <= grp_nbreadreq_fu_164_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((gi_state = ap_const_lv2_2) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_i_i_259_reg_784 <= grp_nbreadreq_fu_164_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nbreadreq_fu_164_p3 = ap_const_lv1_1) and (gi_state = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_reg_809 <= tx_shift2ipv4Fifo_dout(72 downto 64);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_op105_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tx_shift2ipv4Fifo_read_reg_834 <= tx_shift2ipv4Fifo_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln76_2_fu_290_p2 <= std_logic_vector(unsigned(zext_ln76_2_fu_286_p1) + unsigned(ap_const_lv23_40));
    add_ln76_fu_442_p2 <= std_logic_vector(unsigned(zext_ln76_fu_438_p1) + unsigned(ap_const_lv23_40));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, local_ip_address_empty_n, tx_shift2ipv4Fifo_empty_n, ap_predicate_op25_read_state1, ap_predicate_op105_read_state1, tx_udp2ipMetaFifo_empty_n, ap_predicate_op114_read_state1, ap_done_reg, tx_ip2crcFifo_full_n, gi_state_load_reg_780, ap_predicate_op133_write_state2, ap_predicate_op141_write_state2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or (local_ip_address_empty_n = ap_const_logic_0) or ((ap_predicate_op114_read_state1 = ap_const_boolean_1) and (tx_udp2ipMetaFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op105_read_state1 = ap_const_boolean_1) and (tx_shift2ipv4Fifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op25_read_state1 = ap_const_boolean_1) and (tx_shift2ipv4Fifo_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_predicate_op133_write_state2 = ap_const_boolean_1) and (tx_ip2crcFifo_full_n = ap_const_logic_0)) or ((tx_ip2crcFifo_full_n = ap_const_logic_0) and (ap_predicate_op141_write_state2 = ap_const_boolean_1)) or ((gi_state_load_reg_780 = ap_const_lv2_1) and (tx_ip2crcFifo_full_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, local_ip_address_empty_n, tx_shift2ipv4Fifo_empty_n, ap_predicate_op25_read_state1, ap_predicate_op105_read_state1, tx_udp2ipMetaFifo_empty_n, ap_predicate_op114_read_state1, ap_done_reg, tx_ip2crcFifo_full_n, gi_state_load_reg_780, ap_predicate_op133_write_state2, ap_predicate_op141_write_state2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or (local_ip_address_empty_n = ap_const_logic_0) or ((ap_predicate_op114_read_state1 = ap_const_boolean_1) and (tx_udp2ipMetaFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op105_read_state1 = ap_const_boolean_1) and (tx_shift2ipv4Fifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op25_read_state1 = ap_const_boolean_1) and (tx_shift2ipv4Fifo_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_predicate_op133_write_state2 = ap_const_boolean_1) and (tx_ip2crcFifo_full_n = ap_const_logic_0)) or ((tx_ip2crcFifo_full_n = ap_const_logic_0) and (ap_predicate_op141_write_state2 = ap_const_boolean_1)) or ((gi_state_load_reg_780 = ap_const_lv2_1) and (tx_ip2crcFifo_full_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, local_ip_address_empty_n, tx_shift2ipv4Fifo_empty_n, ap_predicate_op25_read_state1, ap_predicate_op105_read_state1, tx_udp2ipMetaFifo_empty_n, ap_predicate_op114_read_state1, ap_done_reg, tx_ip2crcFifo_full_n, gi_state_load_reg_780, ap_predicate_op133_write_state2, ap_predicate_op141_write_state2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or (local_ip_address_empty_n = ap_const_logic_0) or ((ap_predicate_op114_read_state1 = ap_const_boolean_1) and (tx_udp2ipMetaFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op105_read_state1 = ap_const_boolean_1) and (tx_shift2ipv4Fifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op25_read_state1 = ap_const_boolean_1) and (tx_shift2ipv4Fifo_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_predicate_op133_write_state2 = ap_const_boolean_1) and (tx_ip2crcFifo_full_n = ap_const_logic_0)) or ((tx_ip2crcFifo_full_n = ap_const_logic_0) and (ap_predicate_op141_write_state2 = ap_const_boolean_1)) or ((gi_state_load_reg_780 = ap_const_lv2_1) and (tx_ip2crcFifo_full_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(local_ip_address_empty_n, tx_shift2ipv4Fifo_empty_n, ap_predicate_op25_read_state1, ap_predicate_op105_read_state1, tx_udp2ipMetaFifo_empty_n, ap_predicate_op114_read_state1, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or (local_ip_address_empty_n = ap_const_logic_0) or ((ap_predicate_op114_read_state1 = ap_const_boolean_1) and (tx_udp2ipMetaFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op105_read_state1 = ap_const_boolean_1) and (tx_shift2ipv4Fifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op25_read_state1 = ap_const_boolean_1) and (tx_shift2ipv4Fifo_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(tx_ip2crcFifo_full_n, gi_state_load_reg_780, ap_predicate_op133_write_state2, ap_predicate_op141_write_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((ap_predicate_op133_write_state2 = ap_const_boolean_1) and (tx_ip2crcFifo_full_n = ap_const_logic_0)) or ((tx_ip2crcFifo_full_n = ap_const_logic_0) and (ap_predicate_op141_write_state2 = ap_const_boolean_1)) or ((gi_state_load_reg_780 = ap_const_lv2_1) and (tx_ip2crcFifo_full_n = ap_const_logic_0)));
    end process;


    ap_condition_162_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_162 <= ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_175_assign_proc : process(grp_nbreadreq_fu_164_p3, gi_state, icmp_ln76_2_fu_296_p2, icmp_ln82_2_fu_302_p2)
    begin
                ap_condition_175 <= ((grp_nbreadreq_fu_164_p3 = ap_const_lv1_1) and (gi_state = ap_const_lv2_2) and (icmp_ln82_2_fu_302_p2 = ap_const_lv1_1) and (icmp_ln76_2_fu_296_p2 = ap_const_lv1_0));
    end process;


    ap_condition_180_assign_proc : process(grp_nbreadreq_fu_164_p3, gi_state, icmp_ln76_2_fu_296_p2)
    begin
                ap_condition_180 <= ((grp_nbreadreq_fu_164_p3 = ap_const_lv1_1) and (gi_state = ap_const_lv2_2) and (icmp_ln76_2_fu_296_p2 = ap_const_lv1_1));
    end process;


    ap_condition_192_assign_proc : process(gi_state_load_load_fu_253_p1, icmp_ln76_fu_448_p2, icmp_ln82_fu_454_p2)
    begin
                ap_condition_192 <= ((gi_state_load_load_fu_253_p1 = ap_const_lv2_1) and (icmp_ln82_fu_454_p2 = ap_const_lv1_1) and (icmp_ln76_fu_448_p2 = ap_const_lv1_0));
    end process;


    ap_condition_220_assign_proc : process(grp_nbreadreq_fu_164_p3, gi_state, icmp_ln76_2_fu_296_p2, icmp_ln82_2_fu_302_p2)
    begin
                ap_condition_220 <= ((grp_nbreadreq_fu_164_p3 = ap_const_lv1_1) and (gi_state = ap_const_lv2_2) and (icmp_ln82_2_fu_302_p2 = ap_const_lv1_0) and (icmp_ln76_2_fu_296_p2 = ap_const_lv1_0));
    end process;


    ap_condition_232_assign_proc : process(grp_nbreadreq_fu_164_p3, gi_state, grp_fu_236_p3)
    begin
                ap_condition_232 <= ((grp_nbreadreq_fu_164_p3 = ap_const_lv1_1) and (gi_state = ap_const_lv2_3) and (grp_fu_236_p3 = ap_const_lv1_1));
    end process;


    ap_condition_256_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_256 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_phi_ln1027_phi_fu_202_p6_assign_proc : process(gi_state_load_load_fu_253_p1, icmp_ln76_fu_448_p2, icmp_ln82_fu_454_p2, icmp_ln80_fu_624_p2, ap_phi_reg_pp0_iter0_phi_ln1027_reg_199)
    begin
        if ((((gi_state_load_load_fu_253_p1 = ap_const_lv2_1) and (icmp_ln82_fu_454_p2 = ap_const_lv1_0) and (icmp_ln76_fu_448_p2 = ap_const_lv1_0)) or ((gi_state_load_load_fu_253_p1 = ap_const_lv2_1) and (icmp_ln82_fu_454_p2 = ap_const_lv1_1) and (icmp_ln76_fu_448_p2 = ap_const_lv1_0)))) then 
            ap_phi_mux_phi_ln1027_phi_fu_202_p6 <= ap_const_lv1_1;
        elsif (((gi_state_load_load_fu_253_p1 = ap_const_lv2_1) and (icmp_ln76_fu_448_p2 = ap_const_lv1_1))) then 
            ap_phi_mux_phi_ln1027_phi_fu_202_p6 <= icmp_ln80_fu_624_p2;
        else 
            ap_phi_mux_phi_ln1027_phi_fu_202_p6 <= ap_phi_reg_pp0_iter0_phi_ln1027_reg_199;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_currWord_data_V_10_reg_223 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_currWord_data_V_13_reg_212 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_phi_ln1027_reg_199 <= "X";

    ap_predicate_op105_read_state1_assign_proc : process(grp_nbreadreq_fu_164_p3, gi_state)
    begin
                ap_predicate_op105_read_state1 <= ((grp_nbreadreq_fu_164_p3 = ap_const_lv1_1) and (gi_state = ap_const_lv2_3));
    end process;


    ap_predicate_op114_read_state1_assign_proc : process(tmp_i_i_nbreadreq_fu_178_p3, gi_state)
    begin
                ap_predicate_op114_read_state1 <= ((tmp_i_i_nbreadreq_fu_178_p3 = ap_const_lv1_1) and (gi_state = ap_const_lv2_0));
    end process;


    ap_predicate_op133_write_state2_assign_proc : process(gi_state_load_reg_780, tmp_i_i_259_reg_784)
    begin
                ap_predicate_op133_write_state2 <= ((tmp_i_i_259_reg_784 = ap_const_lv1_1) and (gi_state_load_reg_780 = ap_const_lv2_2));
    end process;


    ap_predicate_op141_write_state2_assign_proc : process(gi_state_load_reg_780, tmp_177_i_i_reg_830)
    begin
                ap_predicate_op141_write_state2 <= ((gi_state_load_reg_780 = ap_const_lv2_3) and (tmp_177_i_i_reg_830 = ap_const_lv1_1));
    end process;


    ap_predicate_op25_read_state1_assign_proc : process(grp_nbreadreq_fu_164_p3, gi_state)
    begin
                ap_predicate_op25_read_state1 <= ((grp_nbreadreq_fu_164_p3 = ap_const_lv1_1) and (gi_state = ap_const_lv2_2));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    currWord_data_V_11_fu_382_p1 <= lshr_ln628_8_fu_376_p2(64 - 1 downto 0);
    currWord_data_V_14_fu_266_p1 <= tx_shift2ipv4Fifo_dout(64 - 1 downto 0);
    currWord_data_V_fu_534_p1 <= lshr_ln628_fu_528_p2(64 - 1 downto 0);
    gi_state_load_load_fu_253_p1 <= gi_state;
    grp_fu_236_p3 <= tx_shift2ipv4Fifo_dout(72 downto 72);
    grp_fu_244_p2 <= std_logic_vector(unsigned(header_idx_2) + unsigned(ap_const_lv16_1));
    grp_nbreadreq_fu_164_p3 <= (0=>(tx_shift2ipv4Fifo_empty_n), others=>'-');
    icmp_ln76_2_fu_296_p2 <= "1" when (unsigned(add_ln76_2_fu_290_p2) < unsigned(ap_const_lv23_A1)) else "0";
    icmp_ln76_fu_448_p2 <= "1" when (unsigned(add_ln76_fu_442_p2) < unsigned(ap_const_lv23_A1)) else "0";
    icmp_ln80_fu_624_p2 <= "1" when (select_ln80_fu_616_p3 = ap_const_lv5_0) else "0";
    icmp_ln82_2_fu_302_p2 <= "1" when (unsigned(shl_ln76_2_fu_278_p3) < unsigned(ap_const_lv22_A0)) else "0";
    icmp_ln82_fu_454_p2 <= "1" when (unsigned(shl_ln_fu_430_p3) < unsigned(ap_const_lv22_A0)) else "0";
    len_V_fu_663_p2 <= std_logic_vector(unsigned(meta_length_V_2_fu_647_p4) + unsigned(ap_const_lv16_14));

    local_ip_address_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, local_ip_address_empty_n, ap_done_reg, ap_block_pp0_stage0)
    begin
        if (((ap_done_reg = ap_const_logic_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            local_ip_address_blk_n <= local_ip_address_empty_n;
        else 
            local_ip_address_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    local_ip_address_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_ip_address_read <= ap_const_logic_1;
        else 
            local_ip_address_read <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln628_10_fu_330_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv160_lc_3),to_integer(unsigned('0' & zext_ln628_10_fu_320_p1(31-1 downto 0)))));
    lshr_ln628_6_fu_476_p2 <= std_logic_vector(shift_right(unsigned(header_header_V_2),to_integer(unsigned('0' & zext_ln628_6_fu_468_p1(31-1 downto 0)))));
    lshr_ln628_7_fu_482_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv160_lc_3),to_integer(unsigned('0' & zext_ln628_7_fu_472_p1(31-1 downto 0)))));
    lshr_ln628_8_fu_376_p2 <= std_logic_vector(shift_right(unsigned(header_header_V_2),to_integer(unsigned('0' & zext_ln628_8_fu_372_p1(31-1 downto 0)))));
    lshr_ln628_9_fu_324_p2 <= std_logic_vector(shift_right(unsigned(header_header_V_2),to_integer(unsigned('0' & zext_ln628_9_fu_316_p1(31-1 downto 0)))));
    lshr_ln628_fu_528_p2 <= std_logic_vector(shift_right(unsigned(header_header_V_2),to_integer(unsigned('0' & zext_ln628_fu_524_p1(31-1 downto 0)))));
    meta_length_V_2_fu_647_p4 <= tx_udp2ipMetaFifo_dout(47 downto 32);
    meta_their_address_V_fu_643_p1 <= tx_udp2ipMetaFifo_dout(32 - 1 downto 0);
    or_ln_fu_763_p3 <= (ap_const_lv1_1 & ap_phi_reg_pp0_iter1_currWord_data_V_10_reg_223);
    p_Result_13_fu_727_p5 <= (p_Result_26_fu_715_p5(159 downto 80) & ap_const_lv8_11 & p_Result_26_fu_715_p5(71 downto 0));
    p_Result_24_fu_691_p5 <= (header_header_V_2(159 downto 32) & p_Result_s_fu_683_p3 & header_header_V_2(15 downto 0));
    p_Result_25_fu_703_p5 <= (meta_their_address_V_fu_643_p1 & p_Result_24_fu_691_p5(127 downto 0));
    p_Result_26_fu_715_p5 <= (p_Result_25_fu_703_p5(159 downto 128) & trunc_ln186_fu_249_p1 & p_Result_25_fu_703_p5(95 downto 0));
    p_Result_27_fu_488_p2 <= (lshr_ln628_7_fu_482_p2 and lshr_ln628_6_fu_476_p2);
    p_Result_28_fu_498_p5 <= (ap_const_lv64_0(63 downto 32) & trunc_ln368_fu_494_p1);
    p_Result_29_fu_336_p2 <= (lshr_ln628_9_fu_324_p2 and lshr_ln628_10_fu_330_p2);
    p_Result_30_fu_346_p5 <= (currWord_data_V_14_fu_266_p1(63 downto 32) & trunc_ln368_2_fu_342_p1);
    p_Result_s_fu_683_p3 <= (trunc_ln628_fu_679_p1 & tmp_178_i_i9_fu_669_p4);
    select_ln222_cast_i_i_fu_408_p3 <= 
        ap_const_lv2_3 when (xor_ln222_fu_402_p2(0) = '1') else 
        ap_const_lv2_0;
    select_ln80_fu_616_p3 <= 
        tmp_48_fu_596_p4 when (tmp_47_fu_566_p3(0) = '1') else 
        tmp_49_fu_606_p4;
        sext_ln210_fu_771_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln_fu_763_p3),72));

    shl_ln76_2_fu_278_p3 <= (header_idx_2 & ap_const_lv6_0);
    shl_ln7_fu_544_p3 <= (grp_fu_244_p2 & ap_const_lv6_0);
    shl_ln_fu_430_p3 <= (header_idx_2 & ap_const_lv6_0);
    sub_ln80_3_fu_574_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(trunc_ln80_fu_562_p1));
    sub_ln80_4_fu_590_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(trunc_ln80_8_fu_580_p4));
    sub_ln80_fu_556_p2 <= std_logic_vector(unsigned(ap_const_lv23_A0) - unsigned(zext_ln80_fu_552_p1));
    tmp_178_i_i9_fu_669_p4 <= len_V_fu_663_p2(15 downto 8);
    tmp_46_fu_516_p3 <= (trunc_ln76_fu_422_p1 & ap_const_lv6_0);
    tmp_47_fu_566_p3 <= sub_ln80_fu_556_p2(22 downto 22);
    tmp_48_fu_596_p4 <= sub_ln80_4_fu_590_p2(7 downto 3);
    tmp_49_fu_606_p4 <= sub_ln80_fu_556_p2(10 downto 6);
    tmp_51_fu_460_p3 <= (trunc_ln76_4_fu_426_p1 & ap_const_lv6_0);
    tmp_52_fu_364_p3 <= (trunc_ln76_5_fu_270_p1 & ap_const_lv6_0);
    tmp_53_fu_308_p3 <= (trunc_ln76_6_fu_274_p1 & ap_const_lv6_0);
    tmp_i_i_nbreadreq_fu_178_p3 <= (0=>(tx_udp2ipMetaFifo_empty_n), others=>'-');
    tmp_s_fu_751_p3 <= (tmp_reg_809 & ap_phi_reg_pp0_iter1_currWord_data_V_13_reg_212);
    trunc_ln186_fu_249_p1 <= local_ip_address_dout(32 - 1 downto 0);
    trunc_ln368_2_fu_342_p1 <= p_Result_29_fu_336_p2(32 - 1 downto 0);
    trunc_ln368_fu_494_p1 <= p_Result_27_fu_488_p2(32 - 1 downto 0);
    trunc_ln628_fu_679_p1 <= len_V_fu_663_p2(8 - 1 downto 0);
    trunc_ln76_4_fu_426_p1 <= header_idx_2(2 - 1 downto 0);
    trunc_ln76_5_fu_270_p1 <= header_idx_2(2 - 1 downto 0);
    trunc_ln76_6_fu_274_p1 <= header_idx_2(2 - 1 downto 0);
    trunc_ln76_fu_422_p1 <= header_idx_2(2 - 1 downto 0);
    trunc_ln80_8_fu_580_p4 <= sub_ln80_3_fu_574_p2(10 downto 3);
    trunc_ln80_fu_562_p1 <= sub_ln80_fu_556_p2(11 - 1 downto 0);

    tx_ip2crcFifo_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tx_ip2crcFifo_full_n, gi_state_load_reg_780, ap_predicate_op133_write_state2, ap_predicate_op141_write_state2, ap_block_pp0_stage0)
    begin
        if ((((ap_predicate_op133_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op141_write_state2 = ap_const_boolean_1)) or ((gi_state_load_reg_780 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            tx_ip2crcFifo_blk_n <= tx_ip2crcFifo_full_n;
        else 
            tx_ip2crcFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    tx_ip2crcFifo_din_assign_proc : process(gi_state_load_reg_780, ap_predicate_op133_write_state2, ap_predicate_op141_write_state2, tx_shift2ipv4Fifo_read_reg_834, zext_ln219_fu_758_p1, zext_ln210_fu_775_p1, ap_condition_256)
    begin
        if ((ap_const_boolean_1 = ap_condition_256)) then
            if ((ap_predicate_op141_write_state2 = ap_const_boolean_1)) then 
                tx_ip2crcFifo_din <= tx_shift2ipv4Fifo_read_reg_834;
            elsif ((gi_state_load_reg_780 = ap_const_lv2_1)) then 
                tx_ip2crcFifo_din <= zext_ln210_fu_775_p1;
            elsif ((ap_predicate_op133_write_state2 = ap_const_boolean_1)) then 
                tx_ip2crcFifo_din <= zext_ln219_fu_758_p1;
            else 
                tx_ip2crcFifo_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            tx_ip2crcFifo_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    tx_ip2crcFifo_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, gi_state_load_reg_780, ap_predicate_op133_write_state2, ap_predicate_op141_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_predicate_op133_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op141_write_state2 = ap_const_boolean_1)) or ((gi_state_load_reg_780 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            tx_ip2crcFifo_write <= ap_const_logic_1;
        else 
            tx_ip2crcFifo_write <= ap_const_logic_0;
        end if; 
    end process;


    tx_shift2ipv4Fifo_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tx_shift2ipv4Fifo_empty_n, ap_predicate_op25_read_state1, ap_predicate_op105_read_state1, ap_done_reg, ap_block_pp0_stage0)
    begin
        if ((((ap_done_reg = ap_const_logic_0) and (ap_predicate_op105_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_done_reg = ap_const_logic_0) and (ap_predicate_op25_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            tx_shift2ipv4Fifo_blk_n <= tx_shift2ipv4Fifo_empty_n;
        else 
            tx_shift2ipv4Fifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    tx_shift2ipv4Fifo_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op25_read_state1, ap_predicate_op105_read_state1, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_predicate_op105_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op25_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            tx_shift2ipv4Fifo_read <= ap_const_logic_1;
        else 
            tx_shift2ipv4Fifo_read <= ap_const_logic_0;
        end if; 
    end process;


    tx_udp2ipMetaFifo_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tx_udp2ipMetaFifo_empty_n, ap_predicate_op114_read_state1, ap_done_reg, ap_block_pp0_stage0)
    begin
        if (((ap_done_reg = ap_const_logic_0) and (ap_predicate_op114_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            tx_udp2ipMetaFifo_blk_n <= tx_udp2ipMetaFifo_empty_n;
        else 
            tx_udp2ipMetaFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    tx_udp2ipMetaFifo_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op114_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op114_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            tx_udp2ipMetaFifo_read <= ap_const_logic_1;
        else 
            tx_udp2ipMetaFifo_read <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln222_fu_402_p2 <= (grp_fu_236_p3 xor ap_const_lv1_1);
    zext_ln210_fu_775_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln210_fu_771_p1),128));
    zext_ln219_fu_758_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_751_p3),128));
    zext_ln628_10_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_53_fu_308_p3),160));
    zext_ln628_6_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_51_fu_460_p3),160));
    zext_ln628_7_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_51_fu_460_p3),160));
    zext_ln628_8_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_52_fu_364_p3),160));
    zext_ln628_9_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_53_fu_308_p3),160));
    zext_ln628_fu_524_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_46_fu_516_p3),160));
    zext_ln76_2_fu_286_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln76_2_fu_278_p3),23));
    zext_ln76_fu_438_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_430_p3),23));
    zext_ln80_fu_552_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln7_fu_544_p3),23));
end behav;
