-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rocev2_top_handle_read_requests is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rx_readRequestFifo_dout : IN STD_LOGIC_VECTOR (159 downto 0);
    rx_readRequestFifo_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    rx_readRequestFifo_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    rx_readRequestFifo_empty_n : IN STD_LOGIC;
    rx_readRequestFifo_read : OUT STD_LOGIC;
    rx_remoteMemCmd_din : OUT STD_LOGIC_VECTOR (143 downto 0);
    rx_remoteMemCmd_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
    rx_remoteMemCmd_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
    rx_remoteMemCmd_full_n : IN STD_LOGIC;
    rx_remoteMemCmd_write : OUT STD_LOGIC;
    rx_readEvenFifo_din : OUT STD_LOGIC_VECTOR (161 downto 0);
    rx_readEvenFifo_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
    rx_readEvenFifo_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
    rx_readEvenFifo_full_n : IN STD_LOGIC;
    rx_readEvenFifo_write : OUT STD_LOGIC );
end;


architecture behav of rocev2_top_handle_read_requests is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv48_0 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_580 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010110000000";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv48_580 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000010110000000";
    constant ap_const_lv32_FFFFFA80 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111101010000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv24_1 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal hrr_fsmState_load_load_fu_255_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_nbreadreq_fu_88_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op22_read_state1 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal hrr_fsmState_load_reg_469 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_reg_478 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op62_write_state2 : BOOLEAN;
    signal ap_predicate_op65_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal hrr_fsmState : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal request_vaddr_V : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    signal request_dma_length_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal request_qpn_V : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal request_psn_V : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal rx_readRequestFifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal rx_remoteMemCmd_blk_n : STD_LOGIC;
    signal rx_readEvenFifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln879_fu_267_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln879_reg_482 : STD_LOGIC_VECTOR (23 downto 0);
    signal readLength_fu_271_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal readLength_reg_487 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln879_5_reg_493 : STD_LOGIC_VECTOR (23 downto 0);
    signal readAddr_V_fu_292_p4 : STD_LOGIC_VECTOR (47 downto 0);
    signal readAddr_V_reg_498 : STD_LOGIC_VECTOR (47 downto 0);
    signal trunc_ln186_fu_341_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln186_reg_506 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_request_vaddr_V_new_0_i_phi_fu_119_p4 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln840_11_fu_321_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_reg_pp0_iter0_request_vaddr_V_new_0_i_reg_116 : STD_LOGIC_VECTOR (47 downto 0);
    signal icmp_ln1035_3_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_request_dma_length_V_new_0_i_phi_fu_128_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln841_6_fu_328_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_request_dma_length_V_new_0_i_reg_125 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_request_vaddr_V_flag_2_i_phi_fu_137_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_request_vaddr_V_flag_2_i_reg_134 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1035_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_request_vaddr_V_new_2_i_phi_fu_148_p4 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln840_fu_357_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_reg_pp0_iter0_request_vaddr_V_new_2_i_reg_145 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_mux_request_dma_length_V_new_2_i_phi_fu_158_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln841_fu_364_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_request_dma_length_V_new_2_i_reg_155 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_request_vaddr_V_flag_3_i_phi_fu_168_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_request_vaddr_V_flag_3_i_reg_165 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_request_vaddr_V_new_3_i_phi_fu_182_p6 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_reg_pp0_iter0_request_vaddr_V_new_3_i_reg_179 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_mux_request_dma_length_V_new_3_i_phi_fu_196_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_request_dma_length_V_new_3_i_reg_193 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_readLength_2_reg_207 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_readLength_2_reg_207 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_readOpcode_1_reg_218 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_reg_pp0_iter1_readOpcode_1_reg_218 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_reg_pp0_iter0_readLength_1_reg_231 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_readLength_1_reg_231 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_readOpcode_reg_242 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter1_readOpcode_reg_242 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln840_10_fu_432_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln898_fu_415_p1 : STD_LOGIC_VECTOR (161 downto 0);
    signal zext_ln918_fu_464_p1 : STD_LOGIC_VECTOR (161 downto 0);
    signal tmp_201_i_fu_387_p5 : STD_LOGIC_VECTOR (111 downto 0);
    signal zext_ln871_1_fu_383_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln898_9_i_cast_fu_401_p7 : STD_LOGIC_VECTOR (160 downto 0);
    signal sext_ln871_fu_420_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln871_fu_424_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln918_9_i_cast_fu_448_p7 : STD_LOGIC_VECTOR (160 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_162 : BOOLEAN;
    signal ap_condition_165 : BOOLEAN;
    signal ap_condition_168 : BOOLEAN;
    signal ap_condition_375 : BOOLEAN;
    signal ap_condition_237 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_readLength_1_reg_231_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_162)) then
                if (((hrr_fsmState_load_load_fu_255_p1 = ap_const_lv1_1) and (icmp_ln1035_fu_345_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_readLength_1_reg_231 <= request_dma_length_V;
                elsif (((hrr_fsmState_load_load_fu_255_p1 = ap_const_lv1_1) and (icmp_ln1035_fu_345_p2 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_readLength_1_reg_231 <= ap_const_lv32_580;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_readLength_1_reg_231 <= ap_phi_reg_pp0_iter0_readLength_1_reg_231;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_readLength_2_reg_207_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_162)) then
                if ((ap_const_boolean_1 = ap_condition_168)) then 
                    ap_phi_reg_pp0_iter1_readLength_2_reg_207 <= rx_readRequestFifo_dout(103 downto 72);
                elsif ((ap_const_boolean_1 = ap_condition_165)) then 
                    ap_phi_reg_pp0_iter1_readLength_2_reg_207 <= ap_const_lv32_580;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_readLength_2_reg_207 <= ap_phi_reg_pp0_iter0_readLength_2_reg_207;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_readOpcode_1_reg_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_162)) then
                if ((ap_const_boolean_1 = ap_condition_168)) then 
                    ap_phi_reg_pp0_iter1_readOpcode_1_reg_218 <= ap_const_lv5_10;
                elsif ((ap_const_boolean_1 = ap_condition_165)) then 
                    ap_phi_reg_pp0_iter1_readOpcode_1_reg_218 <= ap_const_lv5_D;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_readOpcode_1_reg_218 <= ap_phi_reg_pp0_iter0_readOpcode_1_reg_218;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_readOpcode_reg_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_162)) then
                if (((hrr_fsmState_load_load_fu_255_p1 = ap_const_lv1_1) and (icmp_ln1035_fu_345_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_readOpcode_reg_242 <= ap_const_lv2_3;
                elsif (((hrr_fsmState_load_load_fu_255_p1 = ap_const_lv1_1) and (icmp_ln1035_fu_345_p2 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_readOpcode_reg_242 <= ap_const_lv2_2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_readOpcode_reg_242 <= ap_phi_reg_pp0_iter0_readOpcode_reg_242;
                end if;
            end if; 
        end if;
    end process;

    hrr_fsmState_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_162)) then
                if (((hrr_fsmState_load_load_fu_255_p1 = ap_const_lv1_1) and (icmp_ln1035_fu_345_p2 = ap_const_lv1_0))) then 
                    hrr_fsmState <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_165)) then 
                    hrr_fsmState <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    request_psn_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_const_boolean_1 = ap_condition_375)) then 
                    request_psn_V <= rx_readRequestFifo_dout(127 downto 104);
                elsif (((hrr_fsmState_load_reg_469 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    request_psn_V <= add_ln840_10_fu_432_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                hrr_fsmState_load_reg_469 <= hrr_fsmState;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                readAddr_V_reg_498 <= rx_readRequestFifo_dout(71 downto 24);
                readLength_reg_487 <= rx_readRequestFifo_dout(103 downto 72);
                trunc_ln186_reg_506 <= trunc_ln186_fu_341_p1;
                trunc_ln879_5_reg_493 <= rx_readRequestFifo_dout(127 downto 104);
                trunc_ln879_reg_482 <= trunc_ln879_fu_267_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_request_vaddr_V_flag_3_i_phi_fu_168_p6 = ap_const_lv1_1))) then
                request_dma_length_V <= ap_phi_mux_request_dma_length_V_new_3_i_phi_fu_196_p6;
                request_vaddr_V <= ap_phi_mux_request_vaddr_V_new_3_i_phi_fu_182_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                request_qpn_V <= trunc_ln879_fu_267_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (hrr_fsmState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_i_reg_478 <= tmp_i_nbreadreq_fu_88_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln840_10_fu_432_p2 <= std_logic_vector(unsigned(request_psn_V) + unsigned(ap_const_lv24_1));
    add_ln840_11_fu_321_p2 <= std_logic_vector(unsigned(readAddr_V_fu_292_p4) + unsigned(ap_const_lv48_580));
    add_ln840_fu_357_p2 <= std_logic_vector(unsigned(request_vaddr_V) + unsigned(ap_const_lv48_580));
    add_ln841_6_fu_328_p2 <= std_logic_vector(unsigned(readLength_fu_271_p4) + unsigned(ap_const_lv32_FFFFFA80));
    add_ln841_fu_364_p2 <= std_logic_vector(unsigned(request_dma_length_V) + unsigned(ap_const_lv32_FFFFFA80));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, rx_readRequestFifo_empty_n, ap_predicate_op22_read_state1, ap_done_reg, rx_remoteMemCmd_full_n, hrr_fsmState_load_reg_469, ap_predicate_op62_write_state2, rx_readEvenFifo_full_n, ap_predicate_op65_write_state2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_predicate_op65_write_state2 = ap_const_boolean_1) and (rx_readEvenFifo_full_n = ap_const_logic_0)) or ((rx_readEvenFifo_full_n = ap_const_logic_0) and (hrr_fsmState_load_reg_469 = ap_const_lv1_1)) or ((ap_predicate_op62_write_state2 = ap_const_boolean_1) and (rx_remoteMemCmd_full_n = ap_const_logic_0)))) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op22_read_state1 = ap_const_boolean_1) and (rx_readRequestFifo_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, rx_readRequestFifo_empty_n, ap_predicate_op22_read_state1, ap_done_reg, rx_remoteMemCmd_full_n, hrr_fsmState_load_reg_469, ap_predicate_op62_write_state2, rx_readEvenFifo_full_n, ap_predicate_op65_write_state2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_predicate_op65_write_state2 = ap_const_boolean_1) and (rx_readEvenFifo_full_n = ap_const_logic_0)) or ((rx_readEvenFifo_full_n = ap_const_logic_0) and (hrr_fsmState_load_reg_469 = ap_const_lv1_1)) or ((ap_predicate_op62_write_state2 = ap_const_boolean_1) and (rx_remoteMemCmd_full_n = ap_const_logic_0)))) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op22_read_state1 = ap_const_boolean_1) and (rx_readRequestFifo_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, rx_readRequestFifo_empty_n, ap_predicate_op22_read_state1, ap_done_reg, rx_remoteMemCmd_full_n, hrr_fsmState_load_reg_469, ap_predicate_op62_write_state2, rx_readEvenFifo_full_n, ap_predicate_op65_write_state2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_predicate_op65_write_state2 = ap_const_boolean_1) and (rx_readEvenFifo_full_n = ap_const_logic_0)) or ((rx_readEvenFifo_full_n = ap_const_logic_0) and (hrr_fsmState_load_reg_469 = ap_const_lv1_1)) or ((ap_predicate_op62_write_state2 = ap_const_boolean_1) and (rx_remoteMemCmd_full_n = ap_const_logic_0)))) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op22_read_state1 = ap_const_boolean_1) and (rx_readRequestFifo_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(rx_readRequestFifo_empty_n, ap_predicate_op22_read_state1, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op22_read_state1 = ap_const_boolean_1) and (rx_readRequestFifo_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(rx_remoteMemCmd_full_n, hrr_fsmState_load_reg_469, ap_predicate_op62_write_state2, rx_readEvenFifo_full_n, ap_predicate_op65_write_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((ap_predicate_op65_write_state2 = ap_const_boolean_1) and (rx_readEvenFifo_full_n = ap_const_logic_0)) or ((rx_readEvenFifo_full_n = ap_const_logic_0) and (hrr_fsmState_load_reg_469 = ap_const_lv1_1)) or ((ap_predicate_op62_write_state2 = ap_const_boolean_1) and (rx_remoteMemCmd_full_n = ap_const_logic_0)));
    end process;


    ap_condition_162_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_162 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_165_assign_proc : process(tmp_i_nbreadreq_fu_88_p3, hrr_fsmState, icmp_ln1035_3_fu_315_p2)
    begin
                ap_condition_165 <= ((tmp_i_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0) and (icmp_ln1035_3_fu_315_p2 = ap_const_lv1_1));
    end process;


    ap_condition_168_assign_proc : process(tmp_i_nbreadreq_fu_88_p3, hrr_fsmState, icmp_ln1035_3_fu_315_p2)
    begin
                ap_condition_168 <= ((tmp_i_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0) and (icmp_ln1035_3_fu_315_p2 = ap_const_lv1_0));
    end process;


    ap_condition_237_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_237 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_375_assign_proc : process(ap_start, tmp_i_nbreadreq_fu_88_p3, hrr_fsmState)
    begin
                ap_condition_375 <= ((tmp_i_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_request_dma_length_V_new_0_i_phi_fu_128_p4_assign_proc : process(rx_readRequestFifo_dout, tmp_i_nbreadreq_fu_88_p3, hrr_fsmState, icmp_ln1035_3_fu_315_p2, add_ln841_6_fu_328_p2, ap_phi_reg_pp0_iter0_request_dma_length_V_new_0_i_reg_125)
    begin
        if (((tmp_i_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0))) then
            if ((icmp_ln1035_3_fu_315_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_request_dma_length_V_new_0_i_phi_fu_128_p4 <= rx_readRequestFifo_dout(103 downto 72);
            elsif ((icmp_ln1035_3_fu_315_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_request_dma_length_V_new_0_i_phi_fu_128_p4 <= add_ln841_6_fu_328_p2;
            else 
                ap_phi_mux_request_dma_length_V_new_0_i_phi_fu_128_p4 <= ap_phi_reg_pp0_iter0_request_dma_length_V_new_0_i_reg_125;
            end if;
        else 
            ap_phi_mux_request_dma_length_V_new_0_i_phi_fu_128_p4 <= ap_phi_reg_pp0_iter0_request_dma_length_V_new_0_i_reg_125;
        end if; 
    end process;


    ap_phi_mux_request_dma_length_V_new_2_i_phi_fu_158_p4_assign_proc : process(hrr_fsmState_load_load_fu_255_p1, icmp_ln1035_fu_345_p2, add_ln841_fu_364_p2, ap_phi_reg_pp0_iter0_request_dma_length_V_new_2_i_reg_155)
    begin
        if (((hrr_fsmState_load_load_fu_255_p1 = ap_const_lv1_1) and (icmp_ln1035_fu_345_p2 = ap_const_lv1_1))) then 
            ap_phi_mux_request_dma_length_V_new_2_i_phi_fu_158_p4 <= add_ln841_fu_364_p2;
        else 
            ap_phi_mux_request_dma_length_V_new_2_i_phi_fu_158_p4 <= ap_phi_reg_pp0_iter0_request_dma_length_V_new_2_i_reg_155;
        end if; 
    end process;


    ap_phi_mux_request_dma_length_V_new_3_i_phi_fu_196_p6_assign_proc : process(hrr_fsmState_load_load_fu_255_p1, tmp_i_nbreadreq_fu_88_p3, hrr_fsmState, ap_phi_mux_request_dma_length_V_new_0_i_phi_fu_128_p4, ap_phi_mux_request_dma_length_V_new_2_i_phi_fu_158_p4, ap_phi_reg_pp0_iter0_request_dma_length_V_new_3_i_reg_193)
    begin
        if (((tmp_i_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0))) then 
            ap_phi_mux_request_dma_length_V_new_3_i_phi_fu_196_p6 <= ap_phi_mux_request_dma_length_V_new_0_i_phi_fu_128_p4;
        elsif ((hrr_fsmState_load_load_fu_255_p1 = ap_const_lv1_1)) then 
            ap_phi_mux_request_dma_length_V_new_3_i_phi_fu_196_p6 <= ap_phi_mux_request_dma_length_V_new_2_i_phi_fu_158_p4;
        else 
            ap_phi_mux_request_dma_length_V_new_3_i_phi_fu_196_p6 <= ap_phi_reg_pp0_iter0_request_dma_length_V_new_3_i_reg_193;
        end if; 
    end process;


    ap_phi_mux_request_vaddr_V_flag_2_i_phi_fu_137_p4_assign_proc : process(hrr_fsmState_load_load_fu_255_p1, ap_phi_reg_pp0_iter0_request_vaddr_V_flag_2_i_reg_134, icmp_ln1035_fu_345_p2)
    begin
        if ((hrr_fsmState_load_load_fu_255_p1 = ap_const_lv1_1)) then
            if ((icmp_ln1035_fu_345_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_request_vaddr_V_flag_2_i_phi_fu_137_p4 <= ap_const_lv1_0;
            elsif ((icmp_ln1035_fu_345_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_request_vaddr_V_flag_2_i_phi_fu_137_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_request_vaddr_V_flag_2_i_phi_fu_137_p4 <= ap_phi_reg_pp0_iter0_request_vaddr_V_flag_2_i_reg_134;
            end if;
        else 
            ap_phi_mux_request_vaddr_V_flag_2_i_phi_fu_137_p4 <= ap_phi_reg_pp0_iter0_request_vaddr_V_flag_2_i_reg_134;
        end if; 
    end process;


    ap_phi_mux_request_vaddr_V_flag_3_i_phi_fu_168_p6_assign_proc : process(hrr_fsmState_load_load_fu_255_p1, tmp_i_nbreadreq_fu_88_p3, hrr_fsmState, ap_phi_mux_request_vaddr_V_flag_2_i_phi_fu_137_p4, ap_phi_reg_pp0_iter0_request_vaddr_V_flag_3_i_reg_165)
    begin
        if (((tmp_i_nbreadreq_fu_88_p3 = ap_const_lv1_0) and (hrr_fsmState = ap_const_lv1_0))) then 
            ap_phi_mux_request_vaddr_V_flag_3_i_phi_fu_168_p6 <= ap_const_lv1_0;
        elsif (((tmp_i_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0))) then 
            ap_phi_mux_request_vaddr_V_flag_3_i_phi_fu_168_p6 <= ap_const_lv1_1;
        elsif ((hrr_fsmState_load_load_fu_255_p1 = ap_const_lv1_1)) then 
            ap_phi_mux_request_vaddr_V_flag_3_i_phi_fu_168_p6 <= ap_phi_mux_request_vaddr_V_flag_2_i_phi_fu_137_p4;
        else 
            ap_phi_mux_request_vaddr_V_flag_3_i_phi_fu_168_p6 <= ap_phi_reg_pp0_iter0_request_vaddr_V_flag_3_i_reg_165;
        end if; 
    end process;


    ap_phi_mux_request_vaddr_V_new_0_i_phi_fu_119_p4_assign_proc : process(rx_readRequestFifo_dout, tmp_i_nbreadreq_fu_88_p3, hrr_fsmState, add_ln840_11_fu_321_p2, ap_phi_reg_pp0_iter0_request_vaddr_V_new_0_i_reg_116, icmp_ln1035_3_fu_315_p2)
    begin
        if (((tmp_i_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0))) then
            if ((icmp_ln1035_3_fu_315_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_request_vaddr_V_new_0_i_phi_fu_119_p4 <= rx_readRequestFifo_dout(71 downto 24);
            elsif ((icmp_ln1035_3_fu_315_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_request_vaddr_V_new_0_i_phi_fu_119_p4 <= add_ln840_11_fu_321_p2;
            else 
                ap_phi_mux_request_vaddr_V_new_0_i_phi_fu_119_p4 <= ap_phi_reg_pp0_iter0_request_vaddr_V_new_0_i_reg_116;
            end if;
        else 
            ap_phi_mux_request_vaddr_V_new_0_i_phi_fu_119_p4 <= ap_phi_reg_pp0_iter0_request_vaddr_V_new_0_i_reg_116;
        end if; 
    end process;


    ap_phi_mux_request_vaddr_V_new_2_i_phi_fu_148_p4_assign_proc : process(hrr_fsmState_load_load_fu_255_p1, icmp_ln1035_fu_345_p2, add_ln840_fu_357_p2, ap_phi_reg_pp0_iter0_request_vaddr_V_new_2_i_reg_145)
    begin
        if (((hrr_fsmState_load_load_fu_255_p1 = ap_const_lv1_1) and (icmp_ln1035_fu_345_p2 = ap_const_lv1_1))) then 
            ap_phi_mux_request_vaddr_V_new_2_i_phi_fu_148_p4 <= add_ln840_fu_357_p2;
        else 
            ap_phi_mux_request_vaddr_V_new_2_i_phi_fu_148_p4 <= ap_phi_reg_pp0_iter0_request_vaddr_V_new_2_i_reg_145;
        end if; 
    end process;


    ap_phi_mux_request_vaddr_V_new_3_i_phi_fu_182_p6_assign_proc : process(hrr_fsmState_load_load_fu_255_p1, tmp_i_nbreadreq_fu_88_p3, hrr_fsmState, ap_phi_mux_request_vaddr_V_new_0_i_phi_fu_119_p4, ap_phi_mux_request_vaddr_V_new_2_i_phi_fu_148_p4, ap_phi_reg_pp0_iter0_request_vaddr_V_new_3_i_reg_179)
    begin
        if (((tmp_i_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0))) then 
            ap_phi_mux_request_vaddr_V_new_3_i_phi_fu_182_p6 <= ap_phi_mux_request_vaddr_V_new_0_i_phi_fu_119_p4;
        elsif ((hrr_fsmState_load_load_fu_255_p1 = ap_const_lv1_1)) then 
            ap_phi_mux_request_vaddr_V_new_3_i_phi_fu_182_p6 <= ap_phi_mux_request_vaddr_V_new_2_i_phi_fu_148_p4;
        else 
            ap_phi_mux_request_vaddr_V_new_3_i_phi_fu_182_p6 <= ap_phi_reg_pp0_iter0_request_vaddr_V_new_3_i_reg_179;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_readLength_1_reg_231 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_readLength_2_reg_207 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_readOpcode_1_reg_218 <= "XXXXX";
    ap_phi_reg_pp0_iter0_readOpcode_reg_242 <= "XX";
    ap_phi_reg_pp0_iter0_request_dma_length_V_new_0_i_reg_125 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_request_dma_length_V_new_2_i_reg_155 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_request_dma_length_V_new_3_i_reg_193 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_request_vaddr_V_flag_2_i_reg_134 <= "X";
    ap_phi_reg_pp0_iter0_request_vaddr_V_flag_3_i_reg_165 <= "X";
    ap_phi_reg_pp0_iter0_request_vaddr_V_new_0_i_reg_116 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_request_vaddr_V_new_2_i_reg_145 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_request_vaddr_V_new_3_i_reg_179 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op22_read_state1_assign_proc : process(tmp_i_nbreadreq_fu_88_p3, hrr_fsmState)
    begin
                ap_predicate_op22_read_state1 <= ((tmp_i_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0));
    end process;


    ap_predicate_op62_write_state2_assign_proc : process(hrr_fsmState_load_reg_469, tmp_i_reg_478)
    begin
                ap_predicate_op62_write_state2 <= ((tmp_i_reg_478 = ap_const_lv1_1) and (hrr_fsmState_load_reg_469 = ap_const_lv1_0));
    end process;


    ap_predicate_op65_write_state2_assign_proc : process(hrr_fsmState_load_reg_469, tmp_i_reg_478)
    begin
                ap_predicate_op65_write_state2 <= ((tmp_i_reg_478 = ap_const_lv1_1) and (hrr_fsmState_load_reg_469 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    hrr_fsmState_load_load_fu_255_p1 <= hrr_fsmState;
    icmp_ln1035_3_fu_315_p2 <= "1" when (unsigned(readLength_fu_271_p4) > unsigned(ap_const_lv32_580)) else "0";
    icmp_ln1035_fu_345_p2 <= "1" when (unsigned(request_dma_length_V) > unsigned(ap_const_lv32_580)) else "0";
    or_ln898_9_i_cast_fu_401_p7 <= (((((ap_const_lv1_1 & trunc_ln879_5_reg_493) & ap_phi_reg_pp0_iter1_readLength_2_reg_207) & ap_const_lv48_0) & trunc_ln879_reg_482) & zext_ln871_1_fu_383_p1);
    or_ln918_9_i_cast_fu_448_p7 <= (((((ap_const_lv1_1 & add_ln840_10_fu_432_p2) & ap_phi_reg_pp0_iter1_readLength_1_reg_231) & ap_const_lv48_0) & request_qpn_V) & zext_ln871_fu_424_p1);
    readAddr_V_fu_292_p4 <= rx_readRequestFifo_dout(71 downto 24);
    readLength_fu_271_p4 <= rx_readRequestFifo_dout(103 downto 72);

    rx_readEvenFifo_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, hrr_fsmState_load_reg_469, rx_readEvenFifo_full_n, ap_predicate_op65_write_state2, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (hrr_fsmState_load_reg_469 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op65_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            rx_readEvenFifo_blk_n <= rx_readEvenFifo_full_n;
        else 
            rx_readEvenFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_readEvenFifo_din_assign_proc : process(hrr_fsmState_load_reg_469, ap_predicate_op65_write_state2, zext_ln898_fu_415_p1, zext_ln918_fu_464_p1, ap_condition_237)
    begin
        if ((ap_const_boolean_1 = ap_condition_237)) then
            if ((hrr_fsmState_load_reg_469 = ap_const_lv1_1)) then 
                rx_readEvenFifo_din <= zext_ln918_fu_464_p1;
            elsif ((ap_predicate_op65_write_state2 = ap_const_boolean_1)) then 
                rx_readEvenFifo_din <= zext_ln898_fu_415_p1;
            else 
                rx_readEvenFifo_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            rx_readEvenFifo_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    rx_readEvenFifo_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, hrr_fsmState_load_reg_469, ap_predicate_op65_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (hrr_fsmState_load_reg_469 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op65_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            rx_readEvenFifo_write <= ap_const_logic_1;
        else 
            rx_readEvenFifo_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_readRequestFifo_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, rx_readRequestFifo_empty_n, ap_predicate_op22_read_state1, ap_done_reg, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_done_reg = ap_const_logic_0) and (ap_predicate_op22_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rx_readRequestFifo_blk_n <= rx_readRequestFifo_empty_n;
        else 
            rx_readRequestFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_readRequestFifo_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op22_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op22_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rx_readRequestFifo_read <= ap_const_logic_1;
        else 
            rx_readRequestFifo_read <= ap_const_logic_0;
        end if; 
    end process;


    rx_remoteMemCmd_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rx_remoteMemCmd_full_n, ap_predicate_op62_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op62_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rx_remoteMemCmd_blk_n <= rx_remoteMemCmd_full_n;
        else 
            rx_remoteMemCmd_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rx_remoteMemCmd_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_201_i_fu_387_p5),144));

    rx_remoteMemCmd_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op62_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op62_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rx_remoteMemCmd_write <= ap_const_logic_1;
        else 
            rx_remoteMemCmd_write <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln871_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_phi_reg_pp0_iter1_readOpcode_reg_242),4));

    tmp_201_i_fu_387_p5 <= (((readLength_reg_487 & ap_const_lv16_0) & readAddr_V_reg_498) & trunc_ln186_reg_506);
    tmp_i_nbreadreq_fu_88_p3 <= (0=>(rx_readRequestFifo_empty_n), others=>'-');
    trunc_ln186_fu_341_p1 <= rx_readRequestFifo_dout(16 - 1 downto 0);
    trunc_ln879_fu_267_p1 <= rx_readRequestFifo_dout(24 - 1 downto 0);
    zext_ln871_1_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter1_readOpcode_1_reg_218),32));
    zext_ln871_fu_424_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln871_fu_420_p1),32));
    zext_ln898_fu_415_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln898_9_i_cast_fu_401_p7),162));
    zext_ln918_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln918_9_i_cast_fu_448_p7),162));
end behav;
