-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rocev2_top_rshiftWordByOctet_net_axis_64_64_13_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rx_exh2aethShiftFifo_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    rx_exh2aethShiftFifo_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    rx_exh2aethShiftFifo_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    rx_exh2aethShiftFifo_empty_n : IN STD_LOGIC;
    rx_exh2aethShiftFifo_read : OUT STD_LOGIC;
    rx_aethSift2mergerFifo_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    rx_aethSift2mergerFifo_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    rx_aethSift2mergerFifo_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    rx_aethSift2mergerFifo_full_n : IN STD_LOGIC;
    rx_aethSift2mergerFifo_write : OUT STD_LOGIC );
end;


architecture behav of rocev2_top_rshiftWordByOctet_net_axis_64_64_13_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv128_lc_2 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001001000";
    constant ap_const_lv32_43 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000011";
    constant ap_const_lv32_44 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal fsmState_load_load_fu_132_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_nbreadreq_fu_72_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op18_read_state1 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal fsmState_load_reg_264 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_reg_278 : STD_LOGIC_VECTOR (0 downto 0);
    signal rs_firstWord_load_reg_285 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op46_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal fsmState : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal prevWord_data_V_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal prevWord_keep_V_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal rs_firstWord : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal rx_exh2aethShiftFifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal rx_aethSift2mergerFifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_Val2_s_reg_268 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Val2_5_reg_273 : STD_LOGIC_VECTOR (7 downto 0);
    signal rs_firstWord_load_load_fu_166_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln628_fu_170_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln628_reg_289 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_111_i7_reg_294 : STD_LOGIC_VECTOR (3 downto 0);
    signal sendWord_last_V_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sendWord_last_V_reg_299 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_sendWord_last_V_1_phi_fu_96_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_sendWord_last_V_1_reg_93 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_rs_firstWord_new_0_i_phi_fu_106_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_rs_firstWord_new_0_i_reg_103 : STD_LOGIC_VECTOR (0 downto 0);
    signal currWord_last_V_fu_158_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal currWord_data_V_fu_144_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln530_fu_242_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln556_fu_259_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_112_i8_fu_184_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_123_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_114_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_106_i_fu_231_p6 : STD_LOGIC_VECTOR (72 downto 0);
    signal zext_ln556_cast_fu_247_p5 : STD_LOGIC_VECTOR (72 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_147 : BOOLEAN;
    signal ap_condition_132 : BOOLEAN;
    signal ap_condition_166 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    fsmState_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_132)) then
                if ((fsmState_load_load_fu_132_p1 = ap_const_lv1_1)) then 
                    fsmState <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_147)) then 
                    fsmState <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                fsmState_load_reg_264 <= fsmState;
                p_Val2_5_reg_273 <= prevWord_keep_V_3;
                p_Val2_s_reg_268 <= prevWord_data_V_4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_72_p3 = ap_const_lv1_1) and (fsmState = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                prevWord_data_V_4 <= currWord_data_V_fu_144_p1;
                prevWord_keep_V_3 <= rx_exh2aethShiftFifo_dout(71 downto 64);
                rs_firstWord <= ap_phi_mux_rs_firstWord_new_0_i_phi_fu_106_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_72_p3 = ap_const_lv1_1) and (fsmState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                rs_firstWord_load_reg_285 <= rs_firstWord;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_72_p3 = ap_const_lv1_1) and (fsmState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (rs_firstWord_load_load_fu_166_p1 = ap_const_lv1_0))) then
                sendWord_last_V_reg_299 <= sendWord_last_V_fu_194_p2;
                tmp_111_i7_reg_294 <= rx_exh2aethShiftFifo_dout(67 downto 64);
                trunc_ln628_reg_289 <= trunc_ln628_fu_170_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (fsmState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_i_reg_278 <= tmp_i_nbreadreq_fu_72_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, rx_exh2aethShiftFifo_empty_n, ap_predicate_op18_read_state1, ap_done_reg, rx_aethSift2mergerFifo_full_n, fsmState_load_reg_264, ap_predicate_op46_write_state2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((fsmState_load_reg_264 = ap_const_lv1_1) and (rx_aethSift2mergerFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op46_write_state2 = ap_const_boolean_1) and (rx_aethSift2mergerFifo_full_n = ap_const_logic_0)))) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op18_read_state1 = ap_const_boolean_1) and (rx_exh2aethShiftFifo_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, rx_exh2aethShiftFifo_empty_n, ap_predicate_op18_read_state1, ap_done_reg, rx_aethSift2mergerFifo_full_n, fsmState_load_reg_264, ap_predicate_op46_write_state2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((fsmState_load_reg_264 = ap_const_lv1_1) and (rx_aethSift2mergerFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op46_write_state2 = ap_const_boolean_1) and (rx_aethSift2mergerFifo_full_n = ap_const_logic_0)))) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op18_read_state1 = ap_const_boolean_1) and (rx_exh2aethShiftFifo_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, rx_exh2aethShiftFifo_empty_n, ap_predicate_op18_read_state1, ap_done_reg, rx_aethSift2mergerFifo_full_n, fsmState_load_reg_264, ap_predicate_op46_write_state2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((fsmState_load_reg_264 = ap_const_lv1_1) and (rx_aethSift2mergerFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op46_write_state2 = ap_const_boolean_1) and (rx_aethSift2mergerFifo_full_n = ap_const_logic_0)))) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op18_read_state1 = ap_const_boolean_1) and (rx_exh2aethShiftFifo_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(rx_exh2aethShiftFifo_empty_n, ap_predicate_op18_read_state1, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op18_read_state1 = ap_const_boolean_1) and (rx_exh2aethShiftFifo_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(rx_aethSift2mergerFifo_full_n, fsmState_load_reg_264, ap_predicate_op46_write_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((fsmState_load_reg_264 = ap_const_lv1_1) and (rx_aethSift2mergerFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op46_write_state2 = ap_const_boolean_1) and (rx_aethSift2mergerFifo_full_n = ap_const_logic_0)));
    end process;


    ap_condition_132_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_132 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_147_assign_proc : process(tmp_i_nbreadreq_fu_72_p3, fsmState, ap_phi_mux_sendWord_last_V_1_phi_fu_96_p4, currWord_last_V_fu_158_p3)
    begin
                ap_condition_147 <= ((tmp_i_nbreadreq_fu_72_p3 = ap_const_lv1_1) and (fsmState = ap_const_lv1_0) and (currWord_last_V_fu_158_p3 = ap_const_lv1_1) and (ap_phi_mux_sendWord_last_V_1_phi_fu_96_p4 = ap_const_lv1_0));
    end process;


    ap_condition_166_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_166 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_rs_firstWord_new_0_i_phi_fu_106_p4_assign_proc : process(tmp_i_nbreadreq_fu_72_p3, fsmState, ap_phi_reg_pp0_iter0_rs_firstWord_new_0_i_reg_103, currWord_last_V_fu_158_p3)
    begin
        if (((tmp_i_nbreadreq_fu_72_p3 = ap_const_lv1_1) and (fsmState = ap_const_lv1_0))) then
            if ((currWord_last_V_fu_158_p3 = ap_const_lv1_0)) then 
                ap_phi_mux_rs_firstWord_new_0_i_phi_fu_106_p4 <= ap_const_lv1_0;
            elsif ((currWord_last_V_fu_158_p3 = ap_const_lv1_1)) then 
                ap_phi_mux_rs_firstWord_new_0_i_phi_fu_106_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_rs_firstWord_new_0_i_phi_fu_106_p4 <= ap_phi_reg_pp0_iter0_rs_firstWord_new_0_i_reg_103;
            end if;
        else 
            ap_phi_mux_rs_firstWord_new_0_i_phi_fu_106_p4 <= ap_phi_reg_pp0_iter0_rs_firstWord_new_0_i_reg_103;
        end if; 
    end process;


    ap_phi_mux_sendWord_last_V_1_phi_fu_96_p4_assign_proc : process(tmp_i_nbreadreq_fu_72_p3, fsmState, rs_firstWord_load_load_fu_166_p1, sendWord_last_V_fu_194_p2, ap_phi_reg_pp0_iter0_sendWord_last_V_1_reg_93)
    begin
        if (((tmp_i_nbreadreq_fu_72_p3 = ap_const_lv1_1) and (fsmState = ap_const_lv1_0))) then
            if ((rs_firstWord_load_load_fu_166_p1 = ap_const_lv1_1)) then 
                ap_phi_mux_sendWord_last_V_1_phi_fu_96_p4 <= ap_const_lv1_0;
            elsif ((rs_firstWord_load_load_fu_166_p1 = ap_const_lv1_0)) then 
                ap_phi_mux_sendWord_last_V_1_phi_fu_96_p4 <= sendWord_last_V_fu_194_p2;
            else 
                ap_phi_mux_sendWord_last_V_1_phi_fu_96_p4 <= ap_phi_reg_pp0_iter0_sendWord_last_V_1_reg_93;
            end if;
        else 
            ap_phi_mux_sendWord_last_V_1_phi_fu_96_p4 <= ap_phi_reg_pp0_iter0_sendWord_last_V_1_reg_93;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_rs_firstWord_new_0_i_reg_103 <= "X";
    ap_phi_reg_pp0_iter0_sendWord_last_V_1_reg_93 <= "X";

    ap_predicate_op18_read_state1_assign_proc : process(tmp_i_nbreadreq_fu_72_p3, fsmState)
    begin
                ap_predicate_op18_read_state1 <= ((tmp_i_nbreadreq_fu_72_p3 = ap_const_lv1_1) and (fsmState = ap_const_lv1_0));
    end process;


    ap_predicate_op46_write_state2_assign_proc : process(fsmState_load_reg_264, tmp_i_reg_278, rs_firstWord_load_reg_285)
    begin
                ap_predicate_op46_write_state2 <= ((rs_firstWord_load_reg_285 = ap_const_lv1_0) and (tmp_i_reg_278 = ap_const_lv1_1) and (fsmState_load_reg_264 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    currWord_data_V_fu_144_p1 <= rx_exh2aethShiftFifo_dout(64 - 1 downto 0);
    currWord_last_V_fu_158_p3 <= rx_exh2aethShiftFifo_dout(72 downto 72);
    fsmState_load_load_fu_132_p1 <= fsmState;
    grp_fu_114_p4 <= p_Val2_s_reg_268(63 downto 32);
    grp_fu_123_p4 <= p_Val2_5_reg_273(7 downto 4);
    rs_firstWord_load_load_fu_166_p1 <= rs_firstWord;

    rx_aethSift2mergerFifo_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rx_aethSift2mergerFifo_full_n, fsmState_load_reg_264, ap_predicate_op46_write_state2, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (fsmState_load_reg_264 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            rx_aethSift2mergerFifo_blk_n <= rx_aethSift2mergerFifo_full_n;
        else 
            rx_aethSift2mergerFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_aethSift2mergerFifo_din_assign_proc : process(fsmState_load_reg_264, ap_predicate_op46_write_state2, zext_ln530_fu_242_p1, zext_ln556_fu_259_p1, ap_condition_166)
    begin
        if ((ap_const_boolean_1 = ap_condition_166)) then
            if ((fsmState_load_reg_264 = ap_const_lv1_1)) then 
                rx_aethSift2mergerFifo_din <= zext_ln556_fu_259_p1;
            elsif ((ap_predicate_op46_write_state2 = ap_const_boolean_1)) then 
                rx_aethSift2mergerFifo_din <= zext_ln530_fu_242_p1;
            else 
                rx_aethSift2mergerFifo_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            rx_aethSift2mergerFifo_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    rx_aethSift2mergerFifo_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, fsmState_load_reg_264, ap_predicate_op46_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (fsmState_load_reg_264 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op46_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            rx_aethSift2mergerFifo_write <= ap_const_logic_1;
        else 
            rx_aethSift2mergerFifo_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_exh2aethShiftFifo_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, rx_exh2aethShiftFifo_empty_n, ap_predicate_op18_read_state1, ap_done_reg, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_done_reg = ap_const_logic_0) and (ap_predicate_op18_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rx_exh2aethShiftFifo_blk_n <= rx_exh2aethShiftFifo_empty_n;
        else 
            rx_exh2aethShiftFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_exh2aethShiftFifo_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op18_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op18_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rx_exh2aethShiftFifo_read <= ap_const_logic_1;
        else 
            rx_exh2aethShiftFifo_read <= ap_const_logic_0;
        end if; 
    end process;

    sendWord_last_V_fu_194_p2 <= "1" when (tmp_112_i8_fu_184_p4 = ap_const_lv4_0) else "0";
    tmp_106_i_fu_231_p6 <= ((((sendWord_last_V_reg_299 & tmp_111_i7_reg_294) & grp_fu_123_p4) & trunc_ln628_reg_289) & grp_fu_114_p4);
    tmp_112_i8_fu_184_p4 <= rx_exh2aethShiftFifo_dout(71 downto 68);
    tmp_i_nbreadreq_fu_72_p3 <= (0=>(rx_exh2aethShiftFifo_empty_n), others=>'-');
    trunc_ln628_fu_170_p1 <= rx_exh2aethShiftFifo_dout(32 - 1 downto 0);
    zext_ln530_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_106_i_fu_231_p6),128));
    zext_ln556_cast_fu_247_p5 <= (((ap_const_lv5_10 & grp_fu_123_p4) & ap_const_lv32_0) & grp_fu_114_p4);
    zext_ln556_fu_259_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln556_cast_fu_247_p5),128));
end behav;
