-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rocev2_top_rx_process_ibh_64_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rx_udp2ibFifo_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    rx_udp2ibFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_udp2ibFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_udp2ibFifo_empty_n : IN STD_LOGIC;
    rx_udp2ibFifo_read : OUT STD_LOGIC;
    rx_ibh2shiftFifo_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    rx_ibh2shiftFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_ibh2shiftFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_ibh2shiftFifo_full_n : IN STD_LOGIC;
    rx_ibh2shiftFifo_write : OUT STD_LOGIC;
    rx_ibh2fsm_MetaFifo_din : OUT STD_LOGIC_VECTOR (118 downto 0);
    rx_ibh2fsm_MetaFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_ibh2fsm_MetaFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_ibh2fsm_MetaFifo_full_n : IN STD_LOGIC;
    rx_ibh2fsm_MetaFifo_write : OUT STD_LOGIC;
    rx_ibh2exh_MetaFifo_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    rx_ibh2exh_MetaFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_ibh2exh_MetaFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_ibh2exh_MetaFifo_full_n : IN STD_LOGIC;
    rx_ibh2exh_MetaFifo_write : OUT STD_LOGIC );
end;


architecture behav of rocev2_top_rx_process_ibh_64_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv128_lc_2 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001001000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv23_40 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000001000000";
    constant ap_const_lv23_60 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000001100000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv96_FFFFFFFFFFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (95 downto 0) := "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv96_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000001111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal tmp_i_nbreadreq_fu_104_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal tmp_i_reg_545 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_reg_545_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_582 : STD_LOGIC_VECTOR (0 downto 0);
    signal bth_ready_load_reg_569 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op82_write_state3 : BOOLEAN;
    signal metaWritten_load_reg_578 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op95_write_state3 : BOOLEAN;
    signal ap_predicate_op96_write_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal bth_ready : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal bth_idx : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal bth_header_V : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal metaWritten : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal rx_udp2ibFifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal rx_ibh2shiftFifo_blk_n : STD_LOGIC;
    signal rx_ibh2fsm_MetaFifo_blk_n : STD_LOGIC;
    signal rx_ibh2exh_MetaFifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal rx_udp2ibFifo_read_reg_549 : STD_LOGIC_VECTOR (127 downto 0);
    signal rx_udp2ibFifo_read_reg_549_pp0_iter1_reg : STD_LOGIC_VECTOR (127 downto 0);
    signal currWord_data_V_fu_224_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal currWord_data_V_reg_554 : STD_LOGIC_VECTOR (63 downto 0);
    signal currWord_last_V_reg_560 : STD_LOGIC_VECTOR (0 downto 0);
    signal bth_ready_load_load_fu_236_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal metaWritten_load_load_fu_248_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_fu_274_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_2_fu_337_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal ap_phi_mux_bth_ready_flag_0_i_phi_fu_142_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_bth_ready_flag_0_i_reg_139 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_bth_idx_new_0_i_phi_fu_153_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln67_fu_283_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_bth_idx_new_0_i_reg_150 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_bth_ready_flag_1_i_phi_fu_163_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_bth_ready_flag_1_i_reg_160 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_bth_idx_flag_1_i_phi_fu_177_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_bth_idx_flag_1_i_reg_174 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_bth_idx_new_1_i_phi_fu_191_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_bth_idx_new_1_i_reg_188 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_metaWritten_flag_1_i_phi_fu_204_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_metaWritten_flag_1_i_reg_201 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_t_reg_215 : STD_LOGIC_VECTOR (95 downto 0);
    signal ap_phi_reg_pp0_iter1_t_reg_215 : STD_LOGIC_VECTOR (95 downto 0);
    signal ap_phi_reg_pp0_iter2_t_reg_215 : STD_LOGIC_VECTOR (95 downto 0);
    signal xor_ln70_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln70_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln70_fu_403_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln70_1_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_376_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal or_ln70_2_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal shl_ln_fu_256_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln58_fu_264_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln58_fu_268_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln58_fu_252_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_291_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln186_fu_280_p1 : STD_LOGIC_VECTOR (95 downto 0);
    signal zext_ln368_fu_299_p1 : STD_LOGIC_VECTOR (95 downto 0);
    signal zext_ln368_2_fu_303_p1 : STD_LOGIC_VECTOR (95 downto 0);
    signal shl_ln368_3_fu_313_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal xor_ln368_1_fu_319_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal shl_ln368_2_fu_307_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal and_ln368_1_fu_325_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal and_ln368_2_fu_331_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal shl_ln368_fu_349_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal xor_ln368_fu_355_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal zext_ln368_1_fu_367_p1 : STD_LOGIC_VECTOR (95 downto 0);
    signal and_ln368_fu_361_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal shl_ln368_1_fu_370_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal trunc_ln668_fu_433_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_i_fu_492_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_19_i_fu_482_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_18_i_fu_472_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_17_i_fu_462_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_16_i_fu_452_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_15_i_fu_442_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_i_fu_502_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_512_p11 : STD_LOGIC_VECTOR (96 downto 0);
    signal sext_ln64_fu_536_p1 : STD_LOGIC_VECTOR (97 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_173 : BOOLEAN;
    signal ap_condition_179 : BOOLEAN;
    signal ap_condition_399 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_t_reg_215_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_179)) then
                if ((ap_const_boolean_1 = ap_condition_173)) then 
                    ap_phi_reg_pp0_iter2_t_reg_215 <= p_Result_2_fu_337_p2;
                elsif (((tmp_i_reg_545 = ap_const_lv1_1) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter2_t_reg_215 <= bth_header_V;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_t_reg_215 <= ap_phi_reg_pp0_iter1_t_reg_215;
                end if;
            end if; 
        end if;
    end process;

    bth_header_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_399)) then
                if ((icmp_ln58_fu_274_p2 = ap_const_lv1_1)) then 
                    bth_header_V <= p_Result_s_fu_376_p2;
                elsif ((icmp_ln58_fu_274_p2 = ap_const_lv1_0)) then 
                    bth_header_V <= p_Result_2_fu_337_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter1_t_reg_215 <= ap_phi_reg_pp0_iter0_t_reg_215;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_reg_545 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln70_1_fu_398_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                bth_idx <= select_ln70_fu_403_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_reg_545 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln70_fu_388_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                bth_ready <= xor_ln70_fu_393_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_reg_545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                bth_ready_load_reg_569 <= bth_ready;
                metaWritten_load_reg_578 <= metaWritten;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_nbreadreq_fu_104_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                currWord_data_V_reg_554 <= currWord_data_V_fu_224_p1;
                currWord_last_V_reg_560 <= rx_udp2ibFifo_dout(72 downto 72);
                rx_udp2ibFifo_read_reg_549 <= rx_udp2ibFifo_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_reg_545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln58_reg_582 <= icmp_ln58_fu_274_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_reg_545 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln70_2_fu_410_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                metaWritten <= xor_ln70_fu_393_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                rx_udp2ibFifo_read_reg_549_pp0_iter1_reg <= rx_udp2ibFifo_read_reg_549;
                tmp_i_reg_545 <= tmp_i_nbreadreq_fu_104_p3;
                tmp_i_reg_545_pp0_iter1_reg <= tmp_i_reg_545;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln58_fu_268_p2 <= std_logic_vector(unsigned(zext_ln58_fu_264_p1) + unsigned(ap_const_lv23_40));
    add_ln67_fu_283_p2 <= std_logic_vector(unsigned(bth_idx) + unsigned(ap_const_lv16_1));
    and_ln368_1_fu_325_p2 <= (xor_ln368_1_fu_319_p2 and bth_header_V);
    and_ln368_2_fu_331_p2 <= (shl_ln368_3_fu_313_p2 and shl_ln368_2_fu_307_p2);
    and_ln368_fu_361_p2 <= (xor_ln368_fu_355_p2 and bth_header_V);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter2, rx_udp2ibFifo_empty_n, tmp_i_nbreadreq_fu_104_p3, ap_done_reg, rx_ibh2shiftFifo_full_n, ap_predicate_op82_write_state3, rx_ibh2fsm_MetaFifo_full_n, ap_predicate_op95_write_state3, rx_ibh2exh_MetaFifo_full_n, ap_predicate_op96_write_state3)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_104_p3 = ap_const_lv1_1) and (rx_udp2ibFifo_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((ap_predicate_op96_write_state3 = ap_const_boolean_1) and (rx_ibh2exh_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op95_write_state3 = ap_const_boolean_1) and (rx_ibh2fsm_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op82_write_state3 = ap_const_boolean_1) and (rx_ibh2shiftFifo_full_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter2, rx_udp2ibFifo_empty_n, tmp_i_nbreadreq_fu_104_p3, ap_done_reg, rx_ibh2shiftFifo_full_n, ap_predicate_op82_write_state3, rx_ibh2fsm_MetaFifo_full_n, ap_predicate_op95_write_state3, rx_ibh2exh_MetaFifo_full_n, ap_predicate_op96_write_state3)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_104_p3 = ap_const_lv1_1) and (rx_udp2ibFifo_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((ap_predicate_op96_write_state3 = ap_const_boolean_1) and (rx_ibh2exh_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op95_write_state3 = ap_const_boolean_1) and (rx_ibh2fsm_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op82_write_state3 = ap_const_boolean_1) and (rx_ibh2shiftFifo_full_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter2, rx_udp2ibFifo_empty_n, tmp_i_nbreadreq_fu_104_p3, ap_done_reg, rx_ibh2shiftFifo_full_n, ap_predicate_op82_write_state3, rx_ibh2fsm_MetaFifo_full_n, ap_predicate_op95_write_state3, rx_ibh2exh_MetaFifo_full_n, ap_predicate_op96_write_state3)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_104_p3 = ap_const_lv1_1) and (rx_udp2ibFifo_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((ap_predicate_op96_write_state3 = ap_const_boolean_1) and (rx_ibh2exh_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op95_write_state3 = ap_const_boolean_1) and (rx_ibh2fsm_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op82_write_state3 = ap_const_boolean_1) and (rx_ibh2shiftFifo_full_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(rx_udp2ibFifo_empty_n, tmp_i_nbreadreq_fu_104_p3, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_104_p3 = ap_const_lv1_1) and (rx_udp2ibFifo_empty_n = ap_const_logic_0)));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_assign_proc : process(rx_ibh2shiftFifo_full_n, ap_predicate_op82_write_state3, rx_ibh2fsm_MetaFifo_full_n, ap_predicate_op95_write_state3, rx_ibh2exh_MetaFifo_full_n, ap_predicate_op96_write_state3)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (((ap_predicate_op96_write_state3 = ap_const_boolean_1) and (rx_ibh2exh_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op95_write_state3 = ap_const_boolean_1) and (rx_ibh2fsm_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op82_write_state3 = ap_const_boolean_1) and (rx_ibh2shiftFifo_full_n = ap_const_logic_0)));
    end process;


    ap_condition_173_assign_proc : process(tmp_i_reg_545, bth_ready_load_load_fu_236_p1, icmp_ln58_fu_274_p2)
    begin
                ap_condition_173 <= ((tmp_i_reg_545 = ap_const_lv1_1) and (icmp_ln58_fu_274_p2 = ap_const_lv1_0) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_0));
    end process;


    ap_condition_179_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_179 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_399_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_i_reg_545, ap_block_pp0_stage0_11001, bth_ready_load_load_fu_236_p1)
    begin
                ap_condition_399 <= ((tmp_i_reg_545 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter2, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_bth_idx_flag_1_i_phi_fu_177_p6_assign_proc : process(tmp_i_reg_545, bth_ready_load_load_fu_236_p1, metaWritten_load_load_fu_248_p1, icmp_ln58_fu_274_p2, ap_phi_mux_bth_ready_flag_0_i_phi_fu_142_p4, ap_phi_reg_pp0_iter1_bth_idx_flag_1_i_reg_174)
    begin
        if ((((tmp_i_reg_545 = ap_const_lv1_1) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_1) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_1)) or ((tmp_i_reg_545 = ap_const_lv1_1) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_0) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_1)) or ((tmp_i_reg_545 = ap_const_lv1_1) and (icmp_ln58_fu_274_p2 = ap_const_lv1_0) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_1)) or ((tmp_i_reg_545 = ap_const_lv1_1) and (icmp_ln58_fu_274_p2 = ap_const_lv1_0) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_0)))) then 
            ap_phi_mux_bth_idx_flag_1_i_phi_fu_177_p6 <= ap_phi_mux_bth_ready_flag_0_i_phi_fu_142_p4;
        elsif (((tmp_i_reg_545 = ap_const_lv1_1) and (icmp_ln58_fu_274_p2 = ap_const_lv1_1) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_0))) then 
            ap_phi_mux_bth_idx_flag_1_i_phi_fu_177_p6 <= ap_const_lv1_1;
        else 
            ap_phi_mux_bth_idx_flag_1_i_phi_fu_177_p6 <= ap_phi_reg_pp0_iter1_bth_idx_flag_1_i_reg_174;
        end if; 
    end process;


    ap_phi_mux_bth_idx_new_0_i_phi_fu_153_p4_assign_proc : process(tmp_i_reg_545, bth_ready_load_load_fu_236_p1, icmp_ln58_fu_274_p2, add_ln67_fu_283_p2, ap_phi_reg_pp0_iter1_bth_idx_new_0_i_reg_150)
    begin
        if (((tmp_i_reg_545 = ap_const_lv1_1) and (icmp_ln58_fu_274_p2 = ap_const_lv1_0) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_0))) then 
            ap_phi_mux_bth_idx_new_0_i_phi_fu_153_p4 <= add_ln67_fu_283_p2;
        else 
            ap_phi_mux_bth_idx_new_0_i_phi_fu_153_p4 <= ap_phi_reg_pp0_iter1_bth_idx_new_0_i_reg_150;
        end if; 
    end process;


    ap_phi_mux_bth_idx_new_1_i_phi_fu_191_p6_assign_proc : process(tmp_i_reg_545, bth_ready_load_load_fu_236_p1, metaWritten_load_load_fu_248_p1, icmp_ln58_fu_274_p2, ap_phi_mux_bth_idx_new_0_i_phi_fu_153_p4, add_ln67_fu_283_p2, ap_phi_reg_pp0_iter1_bth_idx_new_1_i_reg_188)
    begin
        if ((((tmp_i_reg_545 = ap_const_lv1_1) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_1) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_1)) or ((tmp_i_reg_545 = ap_const_lv1_1) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_0) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_1)) or ((tmp_i_reg_545 = ap_const_lv1_1) and (icmp_ln58_fu_274_p2 = ap_const_lv1_0) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_1)) or ((tmp_i_reg_545 = ap_const_lv1_1) and (icmp_ln58_fu_274_p2 = ap_const_lv1_0) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_0)))) then 
            ap_phi_mux_bth_idx_new_1_i_phi_fu_191_p6 <= ap_phi_mux_bth_idx_new_0_i_phi_fu_153_p4;
        elsif (((tmp_i_reg_545 = ap_const_lv1_1) and (icmp_ln58_fu_274_p2 = ap_const_lv1_1) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_0))) then 
            ap_phi_mux_bth_idx_new_1_i_phi_fu_191_p6 <= add_ln67_fu_283_p2;
        else 
            ap_phi_mux_bth_idx_new_1_i_phi_fu_191_p6 <= ap_phi_reg_pp0_iter1_bth_idx_new_1_i_reg_188;
        end if; 
    end process;


    ap_phi_mux_bth_ready_flag_0_i_phi_fu_142_p4_assign_proc : process(tmp_i_reg_545, bth_ready_load_load_fu_236_p1, icmp_ln58_fu_274_p2, ap_phi_reg_pp0_iter1_bth_ready_flag_0_i_reg_139)
    begin
        if ((tmp_i_reg_545 = ap_const_lv1_1)) then
            if (((icmp_ln58_fu_274_p2 = ap_const_lv1_0) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_0))) then 
                ap_phi_mux_bth_ready_flag_0_i_phi_fu_142_p4 <= ap_const_lv1_1;
            elsif ((bth_ready_load_load_fu_236_p1 = ap_const_lv1_1)) then 
                ap_phi_mux_bth_ready_flag_0_i_phi_fu_142_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_bth_ready_flag_0_i_phi_fu_142_p4 <= ap_phi_reg_pp0_iter1_bth_ready_flag_0_i_reg_139;
            end if;
        else 
            ap_phi_mux_bth_ready_flag_0_i_phi_fu_142_p4 <= ap_phi_reg_pp0_iter1_bth_ready_flag_0_i_reg_139;
        end if; 
    end process;


    ap_phi_mux_bth_ready_flag_1_i_phi_fu_163_p6_assign_proc : process(tmp_i_reg_545, bth_ready_load_load_fu_236_p1, metaWritten_load_load_fu_248_p1, icmp_ln58_fu_274_p2, ap_phi_mux_bth_ready_flag_0_i_phi_fu_142_p4, ap_phi_reg_pp0_iter1_bth_ready_flag_1_i_reg_160)
    begin
        if ((((tmp_i_reg_545 = ap_const_lv1_1) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_1) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_1)) or ((tmp_i_reg_545 = ap_const_lv1_1) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_0) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_1)) or ((tmp_i_reg_545 = ap_const_lv1_1) and (icmp_ln58_fu_274_p2 = ap_const_lv1_0) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_1)) or ((tmp_i_reg_545 = ap_const_lv1_1) and (icmp_ln58_fu_274_p2 = ap_const_lv1_0) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_0)))) then 
            ap_phi_mux_bth_ready_flag_1_i_phi_fu_163_p6 <= ap_phi_mux_bth_ready_flag_0_i_phi_fu_142_p4;
        elsif (((tmp_i_reg_545 = ap_const_lv1_1) and (icmp_ln58_fu_274_p2 = ap_const_lv1_1) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_0))) then 
            ap_phi_mux_bth_ready_flag_1_i_phi_fu_163_p6 <= ap_const_lv1_0;
        else 
            ap_phi_mux_bth_ready_flag_1_i_phi_fu_163_p6 <= ap_phi_reg_pp0_iter1_bth_ready_flag_1_i_reg_160;
        end if; 
    end process;


    ap_phi_mux_metaWritten_flag_1_i_phi_fu_204_p6_assign_proc : process(tmp_i_reg_545, bth_ready_load_load_fu_236_p1, metaWritten_load_load_fu_248_p1, icmp_ln58_fu_274_p2, ap_phi_reg_pp0_iter1_metaWritten_flag_1_i_reg_201)
    begin
        if ((((tmp_i_reg_545 = ap_const_lv1_1) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_0) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_1)) or ((tmp_i_reg_545 = ap_const_lv1_1) and (icmp_ln58_fu_274_p2 = ap_const_lv1_0) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_0)))) then 
            ap_phi_mux_metaWritten_flag_1_i_phi_fu_204_p6 <= ap_const_lv1_1;
        elsif ((((tmp_i_reg_545 = ap_const_lv1_1) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_1) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_1)) or ((tmp_i_reg_545 = ap_const_lv1_1) and (icmp_ln58_fu_274_p2 = ap_const_lv1_1) and (bth_ready_load_load_fu_236_p1 = ap_const_lv1_0)) or ((tmp_i_reg_545 = ap_const_lv1_1) and (icmp_ln58_fu_274_p2 = ap_const_lv1_0) and (metaWritten_load_load_fu_248_p1 = ap_const_lv1_1)))) then 
            ap_phi_mux_metaWritten_flag_1_i_phi_fu_204_p6 <= ap_const_lv1_0;
        else 
            ap_phi_mux_metaWritten_flag_1_i_phi_fu_204_p6 <= ap_phi_reg_pp0_iter1_metaWritten_flag_1_i_reg_201;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_t_reg_215 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_bth_idx_flag_1_i_reg_174 <= "X";
    ap_phi_reg_pp0_iter1_bth_idx_new_0_i_reg_150 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_bth_idx_new_1_i_reg_188 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_bth_ready_flag_0_i_reg_139 <= "X";
    ap_phi_reg_pp0_iter1_bth_ready_flag_1_i_reg_160 <= "X";
    ap_phi_reg_pp0_iter1_metaWritten_flag_1_i_reg_201 <= "X";

    ap_predicate_op82_write_state3_assign_proc : process(tmp_i_reg_545_pp0_iter1_reg, icmp_ln58_reg_582, bth_ready_load_reg_569)
    begin
                ap_predicate_op82_write_state3 <= (((bth_ready_load_reg_569 = ap_const_lv1_1) and (tmp_i_reg_545_pp0_iter1_reg = ap_const_lv1_1)) or ((icmp_ln58_reg_582 = ap_const_lv1_0) and (tmp_i_reg_545_pp0_iter1_reg = ap_const_lv1_1)));
    end process;


    ap_predicate_op95_write_state3_assign_proc : process(tmp_i_reg_545_pp0_iter1_reg, icmp_ln58_reg_582, bth_ready_load_reg_569, metaWritten_load_reg_578)
    begin
                ap_predicate_op95_write_state3 <= (((metaWritten_load_reg_578 = ap_const_lv1_0) and (bth_ready_load_reg_569 = ap_const_lv1_1) and (tmp_i_reg_545_pp0_iter1_reg = ap_const_lv1_1)) or ((metaWritten_load_reg_578 = ap_const_lv1_0) and (icmp_ln58_reg_582 = ap_const_lv1_0) and (tmp_i_reg_545_pp0_iter1_reg = ap_const_lv1_1)));
    end process;


    ap_predicate_op96_write_state3_assign_proc : process(tmp_i_reg_545_pp0_iter1_reg, icmp_ln58_reg_582, bth_ready_load_reg_569, metaWritten_load_reg_578)
    begin
                ap_predicate_op96_write_state3 <= (((metaWritten_load_reg_578 = ap_const_lv1_0) and (bth_ready_load_reg_569 = ap_const_lv1_1) and (tmp_i_reg_545_pp0_iter1_reg = ap_const_lv1_1)) or ((metaWritten_load_reg_578 = ap_const_lv1_0) and (icmp_ln58_reg_582 = ap_const_lv1_0) and (tmp_i_reg_545_pp0_iter1_reg = ap_const_lv1_1)));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    bth_ready_load_load_fu_236_p1 <= bth_ready;
    currWord_data_V_fu_224_p1 <= rx_udp2ibFifo_dout(64 - 1 downto 0);
    icmp_ln58_fu_274_p2 <= "1" when (unsigned(add_ln58_fu_268_p2) < unsigned(ap_const_lv23_60)) else "0";
    metaWritten_load_load_fu_248_p1 <= metaWritten;
    or_ln70_1_fu_398_p2 <= (currWord_last_V_reg_560 or ap_phi_mux_bth_idx_flag_1_i_phi_fu_177_p6);
    or_ln70_2_fu_410_p2 <= (currWord_last_V_reg_560 or ap_phi_mux_metaWritten_flag_1_i_phi_fu_204_p6);
    or_ln70_fu_388_p2 <= (currWord_last_V_reg_560 or ap_phi_mux_bth_ready_flag_1_i_phi_fu_163_p6);
    p_Result_2_fu_337_p2 <= (and_ln368_2_fu_331_p2 or and_ln368_1_fu_325_p2);
    p_Result_s_fu_376_p2 <= (shl_ln368_1_fu_370_p2 or and_ln368_fu_361_p2);

    rx_ibh2exh_MetaFifo_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, rx_ibh2exh_MetaFifo_full_n, ap_predicate_op96_write_state3, ap_block_pp0_stage0)
    begin
        if (((ap_predicate_op96_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rx_ibh2exh_MetaFifo_blk_n <= rx_ibh2exh_MetaFifo_full_n;
        else 
            rx_ibh2exh_MetaFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rx_ibh2exh_MetaFifo_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln668_fu_433_p1),32));

    rx_ibh2exh_MetaFifo_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op96_write_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op96_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            rx_ibh2exh_MetaFifo_write <= ap_const_logic_1;
        else 
            rx_ibh2exh_MetaFifo_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_ibh2fsm_MetaFifo_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, rx_ibh2fsm_MetaFifo_full_n, ap_predicate_op95_write_state3, ap_block_pp0_stage0)
    begin
        if (((ap_predicate_op95_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rx_ibh2fsm_MetaFifo_blk_n <= rx_ibh2fsm_MetaFifo_full_n;
        else 
            rx_ibh2fsm_MetaFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rx_ibh2fsm_MetaFifo_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln64_fu_536_p1),119));

    rx_ibh2fsm_MetaFifo_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op95_write_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op95_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            rx_ibh2fsm_MetaFifo_write <= ap_const_logic_1;
        else 
            rx_ibh2fsm_MetaFifo_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_ibh2shiftFifo_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, rx_ibh2shiftFifo_full_n, ap_predicate_op82_write_state3, ap_block_pp0_stage0)
    begin
        if (((ap_predicate_op82_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rx_ibh2shiftFifo_blk_n <= rx_ibh2shiftFifo_full_n;
        else 
            rx_ibh2shiftFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rx_ibh2shiftFifo_din <= rx_udp2ibFifo_read_reg_549_pp0_iter1_reg;

    rx_ibh2shiftFifo_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op82_write_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op82_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            rx_ibh2shiftFifo_write <= ap_const_logic_1;
        else 
            rx_ibh2shiftFifo_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_udp2ibFifo_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, rx_udp2ibFifo_empty_n, tmp_i_nbreadreq_fu_104_p3, ap_done_reg, ap_block_pp0_stage0)
    begin
        if (((ap_done_reg = ap_const_logic_0) and (tmp_i_nbreadreq_fu_104_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rx_udp2ibFifo_blk_n <= rx_udp2ibFifo_empty_n;
        else 
            rx_udp2ibFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_udp2ibFifo_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_104_p3, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_i_nbreadreq_fu_104_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            rx_udp2ibFifo_read <= ap_const_logic_1;
        else 
            rx_udp2ibFifo_read <= ap_const_logic_0;
        end if; 
    end process;

    select_ln70_fu_403_p3 <= 
        ap_const_lv16_0 when (currWord_last_V_reg_560(0) = '1') else 
        ap_phi_mux_bth_idx_new_1_i_phi_fu_191_p6;
        sext_ln64_fu_536_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_512_p11),98));

    shl_ln368_1_fu_370_p2 <= std_logic_vector(shift_left(unsigned(zext_ln368_1_fu_367_p1),to_integer(unsigned('0' & zext_ln368_fu_299_p1(31-1 downto 0)))));
    shl_ln368_2_fu_307_p2 <= std_logic_vector(shift_left(unsigned(zext_ln186_fu_280_p1),to_integer(unsigned('0' & zext_ln368_fu_299_p1(31-1 downto 0)))));
    shl_ln368_3_fu_313_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv96_FFFFFFFFFFFFFFFFFFFFFFFF),to_integer(unsigned('0' & zext_ln368_2_fu_303_p1(31-1 downto 0)))));
    shl_ln368_fu_349_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv96_FFFFFFFFFFFFFFFF),to_integer(unsigned('0' & zext_ln368_fu_299_p1(31-1 downto 0)))));
    shl_ln_fu_256_p3 <= (bth_idx & ap_const_lv6_0);
    tmp_15_i_fu_442_p4 <= ap_phi_reg_pp0_iter2_t_reg_215(63 downto 56);
    tmp_16_i_fu_452_p4 <= ap_phi_reg_pp0_iter2_t_reg_215(55 downto 48);
    tmp_17_i_fu_462_p4 <= ap_phi_reg_pp0_iter2_t_reg_215(47 downto 40);
    tmp_18_i_fu_472_p4 <= ap_phi_reg_pp0_iter2_t_reg_215(95 downto 88);
    tmp_19_i_fu_482_p4 <= ap_phi_reg_pp0_iter2_t_reg_215(87 downto 80);
    tmp_20_i_fu_492_p4 <= ap_phi_reg_pp0_iter2_t_reg_215(79 downto 72);
    tmp_21_i_fu_502_p4 <= ap_phi_reg_pp0_iter2_t_reg_215(31 downto 16);
    tmp_2_fu_512_p11 <= (((((((((ap_const_lv1_1 & tmp_20_i_fu_492_p4) & tmp_19_i_fu_482_p4) & tmp_18_i_fu_472_p4) & tmp_17_i_fu_462_p4) & tmp_16_i_fu_452_p4) & tmp_15_i_fu_442_p4) & tmp_21_i_fu_502_p4) & ap_const_lv24_0) & trunc_ln668_fu_433_p1);
    tmp_fu_291_p3 <= (trunc_ln58_fu_252_p1 & ap_const_lv6_0);
    tmp_i_nbreadreq_fu_104_p3 <= (0=>(rx_udp2ibFifo_empty_n), others=>'-');
    trunc_ln58_fu_252_p1 <= bth_idx(1 - 1 downto 0);
    trunc_ln668_fu_433_p1 <= ap_phi_reg_pp0_iter2_t_reg_215(8 - 1 downto 0);
    xor_ln368_1_fu_319_p2 <= (shl_ln368_3_fu_313_p2 xor ap_const_lv96_FFFFFFFFFFFFFFFFFFFFFFFF);
    xor_ln368_fu_355_p2 <= (shl_ln368_fu_349_p2 xor ap_const_lv96_FFFFFFFFFFFFFFFFFFFFFFFF);
    xor_ln70_fu_393_p2 <= (currWord_last_V_reg_560 xor ap_const_lv1_1);
    zext_ln186_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(currWord_data_V_reg_554),96));
    zext_ln368_1_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(currWord_data_V_reg_554),96));
    zext_ln368_2_fu_303_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_291_p3),96));
    zext_ln368_fu_299_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_291_p3),96));
    zext_ln58_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_256_p3),23));
end behav;
