-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rocev2_top_msn_table is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rxExh2msnTable_upd_req_dout : IN STD_LOGIC_VECTOR (136 downto 0);
    rxExh2msnTable_upd_req_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    rxExh2msnTable_upd_req_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    rxExh2msnTable_upd_req_empty_n : IN STD_LOGIC;
    rxExh2msnTable_upd_req_read : OUT STD_LOGIC;
    txExh2msnTable_req_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    txExh2msnTable_req_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    txExh2msnTable_req_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    txExh2msnTable_req_empty_n : IN STD_LOGIC;
    txExh2msnTable_req_read : OUT STD_LOGIC;
    if2msnTable_init_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    if2msnTable_init_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    if2msnTable_init_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    if2msnTable_init_empty_n : IN STD_LOGIC;
    if2msnTable_init_read : OUT STD_LOGIC;
    msnTable2txExh_rsp_din : OUT STD_LOGIC_VECTOR (55 downto 0);
    msnTable2txExh_rsp_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    msnTable2txExh_rsp_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    msnTable2txExh_rsp_full_n : IN STD_LOGIC;
    msnTable2txExh_rsp_write : OUT STD_LOGIC;
    msnTable2rxExh_rsp_din : OUT STD_LOGIC_VECTOR (151 downto 0);
    msnTable2rxExh_rsp_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    msnTable2rxExh_rsp_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    msnTable2rxExh_rsp_full_n : IN STD_LOGIC;
    msnTable2rxExh_rsp_write : OUT STD_LOGIC );
end;


architecture behav of rocev2_top_msn_table is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_87 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000111";
    constant ap_const_lv32_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal tmp_i_nbreadreq_fu_90_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal tmp_i_reg_364 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_252_nbreadreq_fu_104_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op44_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal tmp_i_reg_364_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_252_reg_392 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_130_i_nbreadreq_fu_118_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op47_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal tmp_i_reg_364_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_252_reg_392_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op81_write_state4 : BOOLEAN;
    signal rxRequest_write_reg_378 : STD_LOGIC_VECTOR (0 downto 0);
    signal rxRequest_write_reg_378_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op88_write_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal msn_table_msn_V_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal msn_table_msn_V_ce1 : STD_LOGIC;
    signal msn_table_msn_V_we1 : STD_LOGIC;
    signal msn_table_msn_V_d1 : STD_LOGIC_VECTOR (23 downto 0);
    signal msn_table_msn_V_q1 : STD_LOGIC_VECTOR (23 downto 0);
    signal msn_table_vaddr_V_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal msn_table_vaddr_V_ce1 : STD_LOGIC;
    signal msn_table_vaddr_V_we1 : STD_LOGIC;
    signal msn_table_vaddr_V_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal msn_table_vaddr_V_q1 : STD_LOGIC_VECTOR (63 downto 0);
    signal msn_table_dma_length_V_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal msn_table_dma_length_V_ce1 : STD_LOGIC;
    signal msn_table_dma_length_V_we1 : STD_LOGIC;
    signal msn_table_dma_length_V_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal msn_table_dma_length_V_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal msn_table_r_key_V_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal msn_table_r_key_V_ce1 : STD_LOGIC;
    signal msn_table_r_key_V_we1 : STD_LOGIC;
    signal msn_table_r_key_V_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal msn_table_r_key_V_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal rxExh2msnTable_upd_req_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal msnTable2rxExh_rsp_blk_n : STD_LOGIC;
    signal txExh2msnTable_req_blk_n : STD_LOGIC;
    signal msnTable2txExh_rsp_blk_n : STD_LOGIC;
    signal if2msnTable_init_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal rxRequest_qpn_V_fu_265_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal rxRequest_qpn_V_reg_368 : STD_LOGIC_VECTOR (15 downto 0);
    signal rxRequest_qpn_V_reg_368_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal rxRequest_dma_length_V_reg_373 : STD_LOGIC_VECTOR (31 downto 0);
    signal rxRequest_dma_length_V_reg_373_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal rxRequest_write_reg_378_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal rxRequest_msn_V_reg_382 : STD_LOGIC_VECTOR (23 downto 0);
    signal rxRequest_msn_V_reg_382_pp0_iter1_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal rxRequest_vaddr_V_reg_387 : STD_LOGIC_VECTOR (63 downto 0);
    signal rxRequest_vaddr_V_reg_387_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal qpn_V_reg_396 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln72_fu_322_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln541_3_fu_330_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln541_fu_335_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ifRequest_qpn_V_fu_307_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to2 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_87 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component rocev2_top_state_table_state_table_req_old_unack_V_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (23 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component rocev2_top_msn_table_msn_table_vaddr_V_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (63 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component rocev2_top_msn_table_msn_table_dma_length_V_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    msn_table_msn_V_U : component rocev2_top_state_table_state_table_req_old_unack_V_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 24,
        AddressRange => 500,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address1 => msn_table_msn_V_address1,
        ce1 => msn_table_msn_V_ce1,
        we1 => msn_table_msn_V_we1,
        d1 => msn_table_msn_V_d1,
        q1 => msn_table_msn_V_q1);

    msn_table_vaddr_V_U : component rocev2_top_msn_table_msn_table_vaddr_V_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 64,
        AddressRange => 500,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address1 => msn_table_vaddr_V_address1,
        ce1 => msn_table_vaddr_V_ce1,
        we1 => msn_table_vaddr_V_we1,
        d1 => msn_table_vaddr_V_d1,
        q1 => msn_table_vaddr_V_q1);

    msn_table_dma_length_V_U : component rocev2_top_msn_table_msn_table_dma_length_V_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 500,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address1 => msn_table_dma_length_V_address1,
        ce1 => msn_table_dma_length_V_ce1,
        we1 => msn_table_dma_length_V_we1,
        d1 => msn_table_dma_length_V_d1,
        q1 => msn_table_dma_length_V_q1);

    msn_table_r_key_V_U : component rocev2_top_msn_table_msn_table_dma_length_V_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 500,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address1 => msn_table_r_key_V_address1,
        ce1 => msn_table_r_key_V_ce1,
        we1 => msn_table_r_key_V_we1,
        d1 => msn_table_r_key_V_d1,
        q1 => msn_table_r_key_V_q1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_op44_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                qpn_V_reg_396 <= txExh2msnTable_req_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_nbreadreq_fu_90_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                rxRequest_dma_length_V_reg_373 <= rxExh2msnTable_upd_req_dout(135 downto 104);
                rxRequest_msn_V_reg_382 <= rxExh2msnTable_upd_req_dout(39 downto 16);
                rxRequest_qpn_V_reg_368 <= rxRequest_qpn_V_fu_265_p1;
                rxRequest_vaddr_V_reg_387 <= rxExh2msnTable_upd_req_dout(103 downto 40);
                rxRequest_write_reg_378 <= rxExh2msnTable_upd_req_dout(136 downto 136);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                rxRequest_dma_length_V_reg_373_pp0_iter1_reg <= rxRequest_dma_length_V_reg_373;
                rxRequest_msn_V_reg_382_pp0_iter1_reg <= rxRequest_msn_V_reg_382;
                rxRequest_qpn_V_reg_368_pp0_iter1_reg <= rxRequest_qpn_V_reg_368;
                rxRequest_vaddr_V_reg_387_pp0_iter1_reg <= rxRequest_vaddr_V_reg_387;
                rxRequest_write_reg_378_pp0_iter1_reg <= rxRequest_write_reg_378;
                tmp_i_reg_364 <= tmp_i_nbreadreq_fu_90_p3;
                tmp_i_reg_364_pp0_iter1_reg <= tmp_i_reg_364;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                rxRequest_write_reg_378_pp0_iter2_reg <= rxRequest_write_reg_378_pp0_iter1_reg;
                tmp_i_252_reg_392_pp0_iter2_reg <= tmp_i_252_reg_392;
                tmp_i_reg_364_pp0_iter2_reg <= tmp_i_reg_364_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_reg_364 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_i_252_reg_392 <= tmp_i_252_nbreadreq_fu_104_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, rxExh2msnTable_upd_req_empty_n, tmp_i_nbreadreq_fu_90_p3, ap_done_reg, txExh2msnTable_req_empty_n, ap_predicate_op44_read_state2, if2msnTable_init_empty_n, ap_predicate_op47_read_state3, msnTable2txExh_rsp_full_n, ap_predicate_op81_write_state4, msnTable2rxExh_rsp_full_n, ap_predicate_op88_write_state4)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op47_read_state3 = ap_const_boolean_1) and (if2msnTable_init_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_predicate_op44_read_state2 = ap_const_boolean_1) and (txExh2msnTable_req_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_90_p3 = ap_const_lv1_1) and (rxExh2msnTable_upd_req_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (((ap_predicate_op88_write_state4 = ap_const_boolean_1) and (msnTable2rxExh_rsp_full_n = ap_const_logic_0)) or ((msnTable2txExh_rsp_full_n = ap_const_logic_0) and (ap_predicate_op81_write_state4 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, rxExh2msnTable_upd_req_empty_n, tmp_i_nbreadreq_fu_90_p3, ap_done_reg, txExh2msnTable_req_empty_n, ap_predicate_op44_read_state2, if2msnTable_init_empty_n, ap_predicate_op47_read_state3, msnTable2txExh_rsp_full_n, ap_predicate_op81_write_state4, msnTable2rxExh_rsp_full_n, ap_predicate_op88_write_state4)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op47_read_state3 = ap_const_boolean_1) and (if2msnTable_init_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_predicate_op44_read_state2 = ap_const_boolean_1) and (txExh2msnTable_req_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_90_p3 = ap_const_lv1_1) and (rxExh2msnTable_upd_req_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (((ap_predicate_op88_write_state4 = ap_const_boolean_1) and (msnTable2rxExh_rsp_full_n = ap_const_logic_0)) or ((msnTable2txExh_rsp_full_n = ap_const_logic_0) and (ap_predicate_op81_write_state4 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, rxExh2msnTable_upd_req_empty_n, tmp_i_nbreadreq_fu_90_p3, ap_done_reg, txExh2msnTable_req_empty_n, ap_predicate_op44_read_state2, if2msnTable_init_empty_n, ap_predicate_op47_read_state3, msnTable2txExh_rsp_full_n, ap_predicate_op81_write_state4, msnTable2rxExh_rsp_full_n, ap_predicate_op88_write_state4)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op47_read_state3 = ap_const_boolean_1) and (if2msnTable_init_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_predicate_op44_read_state2 = ap_const_boolean_1) and (txExh2msnTable_req_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_90_p3 = ap_const_lv1_1) and (rxExh2msnTable_upd_req_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (((ap_predicate_op88_write_state4 = ap_const_boolean_1) and (msnTable2rxExh_rsp_full_n = ap_const_logic_0)) or ((msnTable2txExh_rsp_full_n = ap_const_logic_0) and (ap_predicate_op81_write_state4 = ap_const_boolean_1)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(rxExh2msnTable_upd_req_empty_n, tmp_i_nbreadreq_fu_90_p3, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_90_p3 = ap_const_lv1_1) and (rxExh2msnTable_upd_req_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(txExh2msnTable_req_empty_n, ap_predicate_op44_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((ap_predicate_op44_read_state2 = ap_const_boolean_1) and (txExh2msnTable_req_empty_n = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(if2msnTable_init_empty_n, ap_predicate_op47_read_state3)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((ap_predicate_op47_read_state3 = ap_const_boolean_1) and (if2msnTable_init_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(msnTable2txExh_rsp_full_n, ap_predicate_op81_write_state4, msnTable2rxExh_rsp_full_n, ap_predicate_op88_write_state4)
    begin
                ap_block_state4_pp0_stage0_iter3 <= (((ap_predicate_op88_write_state4 = ap_const_boolean_1) and (msnTable2rxExh_rsp_full_n = ap_const_logic_0)) or ((msnTable2txExh_rsp_full_n = ap_const_logic_0) and (ap_predicate_op81_write_state4 = ap_const_boolean_1)));
    end process;


    ap_condition_87_assign_proc : process(tmp_i_reg_364_pp0_iter1_reg, tmp_i_252_reg_392, tmp_130_i_nbreadreq_fu_118_p3)
    begin
                ap_condition_87 <= ((tmp_130_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (tmp_i_252_reg_392 = ap_const_lv1_0) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter3, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op44_read_state2_assign_proc : process(tmp_i_reg_364, tmp_i_252_nbreadreq_fu_104_p3)
    begin
                ap_predicate_op44_read_state2 <= ((tmp_i_252_nbreadreq_fu_104_p3 = ap_const_lv1_1) and (tmp_i_reg_364 = ap_const_lv1_0));
    end process;


    ap_predicate_op47_read_state3_assign_proc : process(tmp_i_reg_364_pp0_iter1_reg, tmp_i_252_reg_392, tmp_130_i_nbreadreq_fu_118_p3)
    begin
                ap_predicate_op47_read_state3 <= ((tmp_130_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (tmp_i_252_reg_392 = ap_const_lv1_0) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op81_write_state4_assign_proc : process(tmp_i_reg_364_pp0_iter2_reg, tmp_i_252_reg_392_pp0_iter2_reg)
    begin
                ap_predicate_op81_write_state4 <= ((tmp_i_252_reg_392_pp0_iter2_reg = ap_const_lv1_1) and (tmp_i_reg_364_pp0_iter2_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op88_write_state4_assign_proc : process(tmp_i_reg_364_pp0_iter2_reg, rxRequest_write_reg_378_pp0_iter2_reg)
    begin
                ap_predicate_op88_write_state4 <= ((rxRequest_write_reg_378_pp0_iter2_reg = ap_const_lv1_0) and (tmp_i_reg_364_pp0_iter2_reg = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to2)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to2 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    if2msnTable_init_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, if2msnTable_init_empty_n, ap_predicate_op47_read_state3, ap_block_pp0_stage0)
    begin
        if (((ap_predicate_op47_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            if2msnTable_init_blk_n <= if2msnTable_init_empty_n;
        else 
            if2msnTable_init_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    if2msnTable_init_read_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op47_read_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op47_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            if2msnTable_init_read <= ap_const_logic_1;
        else 
            if2msnTable_init_read <= ap_const_logic_0;
        end if; 
    end process;

    ifRequest_qpn_V_fu_307_p1 <= if2msnTable_init_dout(9 - 1 downto 0);

    msnTable2rxExh_rsp_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, msnTable2rxExh_rsp_full_n, ap_predicate_op88_write_state4, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op88_write_state4 = ap_const_boolean_1))) then 
            msnTable2rxExh_rsp_blk_n <= msnTable2rxExh_rsp_full_n;
        else 
            msnTable2rxExh_rsp_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    msnTable2rxExh_rsp_din <= (((msn_table_r_key_V_q1 & msn_table_dma_length_V_q1) & msn_table_vaddr_V_q1) & msn_table_msn_V_q1);

    msnTable2rxExh_rsp_write_assign_proc : process(ap_enable_reg_pp0_iter3, ap_predicate_op88_write_state4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op88_write_state4 = ap_const_boolean_1))) then 
            msnTable2rxExh_rsp_write <= ap_const_logic_1;
        else 
            msnTable2rxExh_rsp_write <= ap_const_logic_0;
        end if; 
    end process;


    msnTable2txExh_rsp_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, msnTable2txExh_rsp_full_n, ap_predicate_op81_write_state4, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op81_write_state4 = ap_const_boolean_1))) then 
            msnTable2txExh_rsp_blk_n <= msnTable2txExh_rsp_full_n;
        else 
            msnTable2txExh_rsp_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    msnTable2txExh_rsp_din <= (msn_table_r_key_V_q1 & msn_table_msn_V_q1);

    msnTable2txExh_rsp_write_assign_proc : process(ap_enable_reg_pp0_iter3, ap_predicate_op81_write_state4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op81_write_state4 = ap_const_boolean_1))) then 
            msnTable2txExh_rsp_write <= ap_const_logic_1;
        else 
            msnTable2txExh_rsp_write <= ap_const_logic_0;
        end if; 
    end process;


    msn_table_dma_length_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_364_pp0_iter1_reg, tmp_i_252_reg_392, tmp_130_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0, rxRequest_write_reg_378_pp0_iter1_reg, zext_ln72_fu_322_p1, zext_ln541_fu_335_p1)
    begin
        if ((((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            msn_table_dma_length_V_address1 <= zext_ln541_fu_335_p1(9 - 1 downto 0);
        elsif (((tmp_130_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (tmp_i_252_reg_392 = ap_const_lv1_0) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            msn_table_dma_length_V_address1 <= zext_ln72_fu_322_p1(9 - 1 downto 0);
        else 
            msn_table_dma_length_V_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    msn_table_dma_length_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_364_pp0_iter1_reg, tmp_i_252_reg_392, tmp_130_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, rxRequest_write_reg_378_pp0_iter1_reg)
    begin
        if ((((tmp_130_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (tmp_i_252_reg_392 = ap_const_lv1_0) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            msn_table_dma_length_V_ce1 <= ap_const_logic_1;
        else 
            msn_table_dma_length_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    msn_table_dma_length_V_d1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_364_pp0_iter1_reg, ap_block_pp0_stage0, rxRequest_dma_length_V_reg_373_pp0_iter1_reg, rxRequest_write_reg_378_pp0_iter1_reg, ap_condition_87)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then
            if (((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_1))) then 
                msn_table_dma_length_V_d1 <= rxRequest_dma_length_V_reg_373_pp0_iter1_reg;
            elsif ((ap_const_boolean_1 = ap_condition_87)) then 
                msn_table_dma_length_V_d1 <= ap_const_lv32_0;
            else 
                msn_table_dma_length_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            msn_table_dma_length_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    msn_table_dma_length_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_364_pp0_iter1_reg, tmp_i_252_reg_392, tmp_130_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, rxRequest_write_reg_378_pp0_iter1_reg)
    begin
        if ((((tmp_130_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (tmp_i_252_reg_392 = ap_const_lv1_0) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            msn_table_dma_length_V_we1 <= ap_const_logic_1;
        else 
            msn_table_dma_length_V_we1 <= ap_const_logic_0;
        end if; 
    end process;


    msn_table_msn_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_364_pp0_iter1_reg, tmp_i_252_reg_392, tmp_130_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0, rxRequest_write_reg_378_pp0_iter1_reg, zext_ln72_fu_322_p1, zext_ln541_3_fu_330_p1, zext_ln541_fu_335_p1)
    begin
        if ((((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            msn_table_msn_V_address1 <= zext_ln541_fu_335_p1(9 - 1 downto 0);
        elsif (((tmp_i_252_reg_392 = ap_const_lv1_1) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            msn_table_msn_V_address1 <= zext_ln541_3_fu_330_p1(9 - 1 downto 0);
        elsif (((tmp_130_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (tmp_i_252_reg_392 = ap_const_lv1_0) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            msn_table_msn_V_address1 <= zext_ln72_fu_322_p1(9 - 1 downto 0);
        else 
            msn_table_msn_V_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    msn_table_msn_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_364_pp0_iter1_reg, tmp_i_252_reg_392, tmp_130_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, rxRequest_write_reg_378_pp0_iter1_reg)
    begin
        if ((((tmp_130_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (tmp_i_252_reg_392 = ap_const_lv1_0) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_252_reg_392 = ap_const_lv1_1) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            msn_table_msn_V_ce1 <= ap_const_logic_1;
        else 
            msn_table_msn_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    msn_table_msn_V_d1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_364_pp0_iter1_reg, ap_block_pp0_stage0, rxRequest_write_reg_378_pp0_iter1_reg, rxRequest_msn_V_reg_382_pp0_iter1_reg, ap_condition_87)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then
            if (((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_1))) then 
                msn_table_msn_V_d1 <= rxRequest_msn_V_reg_382_pp0_iter1_reg;
            elsif ((ap_const_boolean_1 = ap_condition_87)) then 
                msn_table_msn_V_d1 <= ap_const_lv24_0;
            else 
                msn_table_msn_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            msn_table_msn_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    msn_table_msn_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_364_pp0_iter1_reg, tmp_i_252_reg_392, tmp_130_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, rxRequest_write_reg_378_pp0_iter1_reg)
    begin
        if ((((tmp_130_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (tmp_i_252_reg_392 = ap_const_lv1_0) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            msn_table_msn_V_we1 <= ap_const_logic_1;
        else 
            msn_table_msn_V_we1 <= ap_const_logic_0;
        end if; 
    end process;


    msn_table_r_key_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_364_pp0_iter1_reg, tmp_i_252_reg_392, ap_block_pp0_stage0, rxRequest_write_reg_378_pp0_iter1_reg, zext_ln72_fu_322_p1, zext_ln541_3_fu_330_p1, zext_ln541_fu_335_p1, ap_condition_87)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then
            if (((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_0))) then 
                msn_table_r_key_V_address1 <= zext_ln541_fu_335_p1(9 - 1 downto 0);
            elsif (((tmp_i_252_reg_392 = ap_const_lv1_1) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0))) then 
                msn_table_r_key_V_address1 <= zext_ln541_3_fu_330_p1(9 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_87)) then 
                msn_table_r_key_V_address1 <= zext_ln72_fu_322_p1(9 - 1 downto 0);
            else 
                msn_table_r_key_V_address1 <= "XXXXXXXXX";
            end if;
        else 
            msn_table_r_key_V_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    msn_table_r_key_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_364_pp0_iter1_reg, tmp_i_252_reg_392, tmp_130_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, rxRequest_write_reg_378_pp0_iter1_reg)
    begin
        if ((((tmp_130_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (tmp_i_252_reg_392 = ap_const_lv1_0) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_252_reg_392 = ap_const_lv1_1) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            msn_table_r_key_V_ce1 <= ap_const_logic_1;
        else 
            msn_table_r_key_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    msn_table_r_key_V_d1 <= if2msnTable_init_dout(47 downto 16);

    msn_table_r_key_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_364_pp0_iter1_reg, tmp_i_252_reg_392, tmp_130_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_130_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (tmp_i_252_reg_392 = ap_const_lv1_0) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            msn_table_r_key_V_we1 <= ap_const_logic_1;
        else 
            msn_table_r_key_V_we1 <= ap_const_logic_0;
        end if; 
    end process;


    msn_table_vaddr_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_364_pp0_iter1_reg, tmp_i_252_reg_392, tmp_130_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0, rxRequest_write_reg_378_pp0_iter1_reg, zext_ln72_fu_322_p1, zext_ln541_fu_335_p1)
    begin
        if ((((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            msn_table_vaddr_V_address1 <= zext_ln541_fu_335_p1(9 - 1 downto 0);
        elsif (((tmp_130_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (tmp_i_252_reg_392 = ap_const_lv1_0) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            msn_table_vaddr_V_address1 <= zext_ln72_fu_322_p1(9 - 1 downto 0);
        else 
            msn_table_vaddr_V_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    msn_table_vaddr_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_364_pp0_iter1_reg, tmp_i_252_reg_392, tmp_130_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, rxRequest_write_reg_378_pp0_iter1_reg)
    begin
        if ((((tmp_130_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (tmp_i_252_reg_392 = ap_const_lv1_0) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            msn_table_vaddr_V_ce1 <= ap_const_logic_1;
        else 
            msn_table_vaddr_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    msn_table_vaddr_V_d1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_364_pp0_iter1_reg, ap_block_pp0_stage0, rxRequest_write_reg_378_pp0_iter1_reg, rxRequest_vaddr_V_reg_387_pp0_iter1_reg, ap_condition_87)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then
            if (((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_1))) then 
                msn_table_vaddr_V_d1 <= rxRequest_vaddr_V_reg_387_pp0_iter1_reg;
            elsif ((ap_const_boolean_1 = ap_condition_87)) then 
                msn_table_vaddr_V_d1 <= ap_const_lv64_0;
            else 
                msn_table_vaddr_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            msn_table_vaddr_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    msn_table_vaddr_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_364_pp0_iter1_reg, tmp_i_252_reg_392, tmp_130_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, rxRequest_write_reg_378_pp0_iter1_reg)
    begin
        if ((((tmp_130_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (tmp_i_252_reg_392 = ap_const_lv1_0) and (tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (rxRequest_write_reg_378_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            msn_table_vaddr_V_we1 <= ap_const_logic_1;
        else 
            msn_table_vaddr_V_we1 <= ap_const_logic_0;
        end if; 
    end process;


    rxExh2msnTable_upd_req_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, rxExh2msnTable_upd_req_empty_n, tmp_i_nbreadreq_fu_90_p3, ap_done_reg, ap_block_pp0_stage0)
    begin
        if (((ap_done_reg = ap_const_logic_0) and (tmp_i_nbreadreq_fu_90_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rxExh2msnTable_upd_req_blk_n <= rxExh2msnTable_upd_req_empty_n;
        else 
            rxExh2msnTable_upd_req_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rxExh2msnTable_upd_req_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_90_p3, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_i_nbreadreq_fu_90_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            rxExh2msnTable_upd_req_read <= ap_const_logic_1;
        else 
            rxExh2msnTable_upd_req_read <= ap_const_logic_0;
        end if; 
    end process;

    rxRequest_qpn_V_fu_265_p1 <= rxExh2msnTable_upd_req_dout(16 - 1 downto 0);
    tmp_130_i_nbreadreq_fu_118_p3 <= (0=>(if2msnTable_init_empty_n), others=>'-');
    tmp_i_252_nbreadreq_fu_104_p3 <= (0=>(txExh2msnTable_req_empty_n), others=>'-');
    tmp_i_nbreadreq_fu_90_p3 <= (0=>(rxExh2msnTable_upd_req_empty_n), others=>'-');

    txExh2msnTable_req_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, txExh2msnTable_req_empty_n, ap_predicate_op44_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_predicate_op44_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            txExh2msnTable_req_blk_n <= txExh2msnTable_req_empty_n;
        else 
            txExh2msnTable_req_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    txExh2msnTable_req_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op44_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op44_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            txExh2msnTable_req_read <= ap_const_logic_1;
        else 
            txExh2msnTable_req_read <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln541_3_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(qpn_V_reg_396),64));
    zext_ln541_fu_335_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rxRequest_qpn_V_reg_368_pp0_iter1_reg),64));
    zext_ln72_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ifRequest_qpn_V_fu_307_p1),64));
end behav;
